### ISSUE TITLE
Gain / Loss have been reversed in Tidal Wetland Change layer

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#1029]
In the Tidal Wetland Change contextual layer, the loss has been visualised as gain and vice-versa. Could this be addressed with urgency?

GMW:
![afbeelding](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/b011c05f-dee8-4d98-a9fc-1ce9faef1972)

Original:
![afbeelding](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/b8b2d1c1-0de5-4656-8c2b-c48db863bd61)

**Comment by dhakelila** [comment]
We'll take care of it asap

**Comment by AngelArcones** [comment]
@lhilarides @dhakelila This is now fixed in staging and production
