### ISSUE TITLE
When trying to move the map, user drags the logo

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#1078]
When a user tries to pan the map by clicking on the map just below the logo (in the transparent part of the png), the cursor picks up the logo, instead of panning the map.

![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/e3431f8d-5892-4b39-955e-b231f007e5c5)

**Comment by klongleywood** [comment]
Tested and confirmed QC
