### ISSUE TITLE
Name of previous geometry remains visible when calculating "Custom area"

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#1085]
When doing a custom area calculation, the name of the previously selected geometry remains visible. In the past this was replaced by "Custom area"

![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/8dd99500-981b-4fd9-a4be-64eee7dc84af)

**Comment by mluena** [comment]
I've tried to replicate this but it's working for me. @lhilarides I am not sure if you have the correct link for staging, https://staging-mangrove-atlas.vercel.app/ the delete should not appear there either

**Comment by lhilarides** [comment]
This seems to be fixed now, as I can no longer reproduce it. Closing the issue
