### ISSUE TITLE
Mangrove alerts widget: show only years, instead of all months

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#1087]
There are too many months to show individually, so I think showing only years (from 2019 until the year of "today") is better

![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/473fc6c4-1990-4095-ad31-426673df9a93)

**Comment by mluena** [comment]
I've done a combination of both, all years at the bottom. And months on the top chart

**Comment by klongleywood** [comment]
I think it would be ok to just include the top chart with the fix of having only every few months labeled. What do you think @lhilarides
