### ISSUE TITLE
Client side application errors

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#1088]
Every now and then the app crashes. This happens especially after using the app for a while. The error is typically:

"Application error: a client-side exception has occurred (see the browser console for more information)."

According to Google Analytics, 0.16% of our page views result in an application error like this. It's not terrible, but also not good: if we assume 10 page views per visit then 1 in every 60 visits has a crash.

I've managed to capture one of those crashes on the console, and the error relates to the undefined variable:

mng_mjr_undefined , which seems to point to a situation where the year of the mangrove extent is not defined and also there's no default or fallback year 

A quick search in the repo for "mng_mjr" points to this file

[src/containers/datasets/habitat-extent/hooks.tsx](https://github.com/Vizzuality/mangrove-atlas/blob/3ced57429f34a8784e33737e9affed2d2c330ec8/src/containers/datasets/habitat-extent/hooks.tsx#L240)

For reference, the full error message: 

Error: Source layer "mng_mjr_undefined" does not exist on source "habitat_extent" as specified by style layer "mangrove_habitat_extent_undefined_line"
    NextJS 31
        _validateLayer
        addLayer
        addLayer
        createLayer
        components_layer
        Xh
        x
        Vk
        Hk
        Hk
        J
        R
        60053
        __webpack_require__
        63840
        __webpack_require__
        64448
        __webpack_require__
        73935
        __webpack_require__
        20745
        __webpack_require__
        91078
        __webpack_require__
        56003
        __webpack_require__
        <anonymous>
        O
        <anonymous>
        c
        <anonymous>
_app-5c4e15791eae0edf.js:14:68891
    NextJS 36

**Comment by mluena** [comment]
I've made a fix, please let me know if the issue still occurs

**Comment by klongleywood** [comment]
@mluena and fyi @lhilarides I had this happen repeatedly when trying to upload a custom area shapefile

**Comment by lhilarides** [comment]
I just tested this and was able to reproduce the exact same error:

```
Error: Source layer "mng_mjr_undefined" does not exist on source "habitat_extent" as specified by style layer "mangrove_habitat_extent_undefined_line"
    NextJS 12
        _validateLayer
        addLayer
        addLayer
        tF
        tz
        ab
        i
        oO
        oS
        oS
        x
        T
www.globalmangrovewatch.org:12714:25
```

However, since there's been a complete refactoring of the code anyway in staging, I suggest that maybe we close this one and focus our efforts on fixing the last remaining issues there

**Comment by mluena** [comment]
I am deploying a fix for production environment

**Comment by klongleywood** [comment]
@mluena and fyi @lhilarides I'm still experiencing this issue, but since Maria is deploying a fix for production and Lammert suggests we close it, I closed it
