### ISSUE TITLE
Inconsistent language regarding "widgets"

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#1089]
We currently use the following terms to refer to the "widgets":
1. Widgets deck
2. Data cards
3. Data deck
4. Widget

To prevent confusion, we should be consistent and choose one term to use everywhere. To me, "Data cards" seems like the most logical term to use, but I'm no native speaker. What's your take on this @klongleywood ?

**Comment by lhilarides** [comment]
We agreed to use the terms "Widget" and "Widgets deck" to keep in line with all our other reports, training material and documentation

**Comment by klongleywood** [comment]
Tested and confirmed QC
