### ISSUE TITLE
National dashboards dropdown menu's are not consistent with rest of site

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#1090]
The dropdown menu in the national dashboards are inconsistent with the dropdown menu's on the rest of the site. Please harmonise the design of the national dashboard with the rest of the site

National dashboard:
![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/d7b69cd3-82f3-47b5-b955-e03853614e0b)

Mangrove extent:
![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/0ebda475-ad27-4787-9d18-0c2c868ce288)

**Comment by klongleywood** [comment]
Tested and confirmed QC
