### ISSUE TITLE
"Customize widgets deck" widget remains visible, also after deselecting it

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#1091]
When selecting the widgets and layers, the "Customize widgets deck" always remains visible, also when explicitly deselected from the list

![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/8ea48324-bfd7-4045-9d29-c7e75dda0989)

**Comment by klongleywood** [comment]
@mluena I see that "Customize widget deck" is no longer on the list -- was this intentional? I think it's ok but just wanted to check that it wasn't an oversight 

fyi @lhilarides

**Comment by mluena** [comment]
Yes @klongleywood, this was intentional as it should never have been there
