### ISSUE TITLE
Planet imagery layers are added on top of other layers

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#1092]
When a Planet Imagery background layer is added, the layer appears on top in the map, instead of the bottom of the layer stack. This makes other layers invisible

![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/c666efe7-97b0-45d2-a3a9-2e69c82e9fe8)

**Comment by klongleywood** [comment]
Tested and confirmed QC
