### ISSUE TITLE
When layers are not available at a certain level (global/country/site) add a popup to the data selection menu

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#1097]
When layers are not available at a certain level (global/country/site) add a popup to the data selection menu, as below:
![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/1b49b2be-aceb-44c9-911c-d0694946a1ed)

**Comment by mluena** [comment]
We added a disclaimer between the presets and the list.
![Screenshot 2024-04-23 at 10 16 17](https://github.com/Vizzuality/mangrove-atlas/assets/33252015/4d6f6770-5557-42e4-ba19-d0121d786cb7)

**Comment by klongleywood** [comment]
Could we add to the end of this blurb "Select applicable geography to enable layer".  

fyi @lhilarides
