### ISSUE TITLE
App Crashes when X button is clicked

### ISSUE THREAD

**Issue by klongleywood** [Vizzuality/mangrove-atlas#1098]
@dhakelila and @mluena 

I've noticed that often when I click one of the X buttons to close a pop-up window in the staging app, the entire application window closes. This happens most frequently when I'm trying to close the basemaps window (see below) but I've been noticing it in other locations as well. 

![image](https://github.com/Vizzuality/mangrove-atlas/assets/54109064/94cf5320-ae4c-4d71-aad5-28d3043e5c81)

**Comment by mluena** [comment]
I'll take a look ASAP
