### ISSUE TITLE
National Dashboard: selecting a new layer from the same source duplicates legend

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#1109]
Behaviour of the National Dashboard widget is not consistent. The problem shows when for example you go to Mexico's National Dashboard and enable the CONABIO layer. This shows the layer on the map and adds a legend item. So far so good. However, when you select a different layer (e.g. 1970) from the same source, it seems to add a layer with the same color but leaves it disabled. 

I think it's best to keep it simple for now and just show a single layer for each source, so when you select 1970 it is automatically enabled, shown on the map and in the legend and the previous layer/year is disabled and disappears.

One more small fix: the styling of the dropdown can be improved by adding a border (basically copy the styling from other dropdown elements)

Also see the screenshot below for the current situation:
![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/f72010ec-cd65-451a-955f-91b882dd517e)

**Comment by klongleywood** [comment]
QC'd - confirmed that issue was fixed
