### ISSUE TITLE
Restoration sites widget issues(2)

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#1111]
The restoration **sites** widget has the following issues:
- the widget seems to have the wrong map layer associated with it (the restoration layer instead of the restoration sites layer)
- when using the filter in the widget: if the number of results is zero an error message is displayed, which is good, but the option to reset the filter disappears so users can no longer reset the filter. See screenshot below:

![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/d1eb157d-42e2-4e0a-b912-5430088996ce)

**Comment by mluena** [comment]
First issue solved, second one WIP

**Comment by klongleywood** [comment]
QA'd first issue confirmed that it is solved
