### ISSUE TITLE
Slider Bar for mangrove species stuck at 1

### ISSUE THREAD

**Issue by klongleywood** [Vizzuality/mangrove-atlas#1130]
In the mangrove species distribution widget, the black triangle at the top of the slider should correspond to the # of species, but it seems to be stuck at 1. For example, in the image below, the black triangle should be to the right of the slider rather than all the way to the left. 

@mluena and fyi @lhilarides 

![image](https://github.com/Vizzuality/mangrove-atlas/assets/54109064/3168515d-616b-47d2-9372-c5760cc29011)

**Comment by mluena** [comment]
Fixed! @klongleywood
