### ISSUE TITLE
Planet API key updated on Heroku but not reflected on the live site

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#1140]
I've had to update the Planet API key in the Heroku config variables recently. I've restarted the dynos, just to be sure the new config var would be loaded, but somehow it seems to still use the old key. Do we use some kind of caching mechanism?

Problem is quite visible on the live site (for me at least): with the planet layer enabled zoom in as far as you can and you'll see the following message: 
![image](https://github.com/user-attachments/assets/b6597a04-9c32-4969-bf6f-307bf9c23060)

I've tried this API key also in QGIS and it works perfectly fine there

**Comment by mluena** [comment]
I ve just checked [prod](https://www.globalmangrovewatch.org/country/GMB?category=%22contextual_layers%22&active=[%22mangrove_restoration%22,%22mangrove_tidal_flats%22,%22mangrove_habitat_extent%22]&bounds=[[-51.82049591180606,-13.247676765730404],[26.029104596111267,20.71202395131681]]&basemaps-contextual=%22planet_medres_visual_monthly%22) and I can't see that warning

**Comment by mluena** [comment]
I can't get in Heroku right now, have you changed for both environments? I experience this warning just in staging and not in prod

**Comment by lhilarides** [comment]
I've updated both. You only get this message beyond a certain zoom level. Low zoom levels are still served normally by Planet. 

I can reproduce this in different browsers on multiple machines and any location that I zoom to, so it's unlikely to be a client side issue

**Comment by mluena** [comment]
I am waiting for Heroku support to unlock my account, try to redeploy both sites if you can let me know if you need any help with this

**Comment by lhilarides** [comment]
Just redeployed production and the problem was fixed immediately, thanks!
