### ISSUE TITLE
App crashes when flying to location

### ISSUE THREAD

**Issue by mluena** [Vizzuality/mangrove-atlas#1142]
### Current Behavior:
App crashes every time the map flies to a location (from both clicking on the map or search tool)

### Expected Behavior:
Map flies smoothly to a location when selected

**Comment by mluena** [comment]
This should be now fixed @lhilarides @klongleywood

**Comment by mluena** [comment]
@lhilarides @klongleywood

**Comment by lhilarides** [comment]
This seems to have been fixed now. I no longer have permission to close issues it seems, so will have to leave that to you @mluena

**Comment by mluena** [comment]
great, I am closing the issue then, reopen it if at any point you experience any problem
