### ISSUE TITLE
Mangrove Biomass Layer not working (staging)

### ISSUE THREAD

**Issue by klongleywood** [Vizzuality/mangrove-atlas#1159]
The Mangrove Biomass layer does not appear on the map when it is toggled on. I noticed this first when trying to calculate stats for a custom area and it had an error message saying no data were available for that region. When I zoom back to Worldwide, it still is not appearing on the map. 

@mluena and fyi @lhilarides

**Comment by klongleywood** [comment]
Now it seems to working....

**Comment by mluena** [comment]
I just fixed it
