### ISSUE TITLE
Provide download metadata

### ISSUE THREAD

**Issue by dhakelila** [Vizzuality/mangrove-atlas#283]
Please, @lhilarides, provide a file by Friday 16th July with the desired metadata to show when the user opens a "download panel".
Information that panel might include:

File name
Description (optional)
License (optional)
Link
Our understanding is that you will provide the links for all the downloadable files.

**Comment by klongleywood** [comment]
I'm working on this today -- will have you something by COB!

**Comment by klongleywood** [comment]
Hi all, please see this spreadsheet for this info: https://wetlandsint.sharepoint.com/:x:/s/GlobalMangroveWatch/EYREU2G0OflJmGn3OD13JscBqviN3B_jHPOHQmDieyanIQ?email=clara.linos%40vizzuality.com&e=dnCxqd

**Comment by dhakelila** [comment]
@mluena, @danicaso-vizzuality 
I created a google spreadsheet with the data in our shared drive folder. 
https://docs.google.com/spreadsheets/d/1F70J0GWlrPDMD7dYE7O20tAGtCKiEo_qnZygi0AE0lA
