### ISSUE TITLE
[Climate Mitigation and Policy] - Proposal feedback. 

### ISSUE THREAD

**Issue by dhakelila** [Vizzuality/mangrove-atlas#291]
Please @klongleywood, share [our proposal](https://github.com/Vizzuality/mangrove-atlas/discussions/285) with your colleagues.

It would be good to be able to discuss this during our next call. If that is not possible, please propose an alternative deadline.

**Comment by klongleywood** [comment]
We discussed this with our internal team today, and one comment was that we may like to add an indicator of what % of forests are mangroves to add more context to the FREL tab. 

That said, we'd like to bring this proposal to our climate and policy working group and we are planning a call with them for mid-late August. Given that we're no longer rushing to get this out, this gives us a bit more time to think about other design and data features we may want to add, and we can discuss more on Tuesday.
