### ISSUE TITLE
Bugs reporting

### ISSUE THREAD

**Issue by dhakelila** [Vizzuality/mangrove-atlas#314]
Hi @klongleywood , @lhilarides , we discussed some bugs during our last week and we agreed those will be reported here in Github. I wanted to know if that is still the idea as I can't find them.

**Comment by lhilarides** [comment]
Hi Clara! Yes, still the plan. I will file them later today. I'd also like
to transfer the repository, so would be great if you give me the
permissions to do so. Thanks!
Lammert

**Comment by dhakelila** [comment]
Hey Lammert, for the transfer, I understood that we'd wait until the development has started just in case there is something to adapt to the Heroku automatizations. 

I'm giving you permission. But I'd recommend waiting.
