### ISSUE TITLE
Mangrove height widget doesn't add up to 100% in all countries

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#315]
The sum of percentages of the different classes should always add up to 100%. Seems like a mistake was made in calculations. See e.g. Indonesia:
![image](https://user-images.githubusercontent.com/3919721/134411279-fe664a87-181b-4aef-b21d-ce6387ddcc7a.png)

**Comment by mluena** [comment]
Legend values changed, numbers added up according to legend values (data pending to be reviewed)

 ![Screenshot 2021-11-18 at 10 30 09](https://user-images.githubusercontent.com/33252015/142388731-9c78c490-a029-43ae-9708-4a551b4a2207.png)
