### ISSUE TITLE
Mangrove biomass widget

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#317]
In the AsiaPacific region the fist interval is wrong (0-2500 instead of 0-250) which influences the whole pie chart

![image](https://user-images.githubusercontent.com/3919721/134413109-18927add-1945-4a25-9037-e4d251a71e51.png)

**Comment by mluena** [comment]
Extra 0s in legend removed, legend limited to existing values (data pending to be reviewed):

![Screenshot 2021-11-18 at 10 34 30](https://user-images.githubusercontent.com/33252015/142389390-6b3a506f-9f43-4740-b9aa-174de15abac8.png)
