### ISSUE TITLE
Mangrove biomass map

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#318]
On the map it looks like the mangrove extent layer is now on top of the mangrove biomass layer when both are displayed. The biomass layer should be on top, see below

![image](https://user-images.githubusercontent.com/3919721/134413720-e3d4670a-a1e5-4b57-bef9-33c8baeb4472.png)

**Comment by mluena** [comment]
Addressed

![Screenshot 2021-11-18 at 10 36 32](https://user-images.githubusercontent.com/33252015/142389699-ec49314a-7b6d-4309-877a-44a89c5f24ba.png)
