### ISSUE TITLE
Browser window resize resets zoom to global level

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#320]
When you are zoomed into a country and you resize the browser window, the platform automatically zooms out to a Worldview. You then have to navigate out of the country (select for example another country) and back into the country, you can’t just re-select the country you were zoomed into. The zoom doesn't need to be reset at all when resizing the browser

**Comment by dhakelila** [comment]
@lhilarides this works correctly for me. Can you confirm? 
If' it's working, please, close the issue.

**Comment by lhilarides** [comment]
I've just tested in in Chrome and Firefox on Windows 10, but in both cases the bug is still there. Steps to reproduce:
1. Open the site
2. Click on a country so the map zooms in to that country
3. Resize the window
4. You'll be zoomed out

**Comment by dhakelila** [comment]
@klongleywood ready for testing

**Comment by lhilarides** [comment]
It seems to work fine for me on staging now. Can you try using your setup @klongleywood and close if it's fixed?

**Comment by klongleywood** [comment]
Works for me
