### ISSUE TITLE
Mangrove Habitat Change widget: remove on/off button

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#325]
There is no geospatial layer associated with the "Mangrove Habitat Change" widget, so the on/off button can be removed:

![image](https://user-images.githubusercontent.com/3919721/135124207-3a28f8cf-1d3e-4203-9926-da8559512d7a.png)

**Comment by mluena** [comment]
![Screenshot 2021-11-18 at 10 39 21](https://user-images.githubusercontent.com/33252015/142390103-fec1ae13-49c9-4892-adbd-5309b4737f4b.png)
