### ISSUE TITLE
New version of country boundaries (GADM + EEZ)

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#329]
There has been an update of the GADM country boundaries + Economic Zone dataset. From now on, please use the layer in the link below for the analysis of all layers and widgets. This has been aligned with other organisations so we all produce the same statistics.

https://www.dropbox.com/s/024py30z3v9h3lb/GADM_EEZ_WCMC-300321.zip?dl=0

**Comment by tamaramegan** [comment]
@lhilarides the link provided shoes the message 'The file has been deleted'. Could you please send us the file again?

**Comment by tamaramegan** [comment]
@lhilarides Alicia had already downloaded this before the file was deleted, so you can ignore the previous message.

**Comment by dhakelila** [comment]
@aagm , it seems this task was not completed. Can you check?

**Comment by dhakelila** [comment]
@lhilarides could you share the new GADM geometries you'd like us to use?

**Comment by lhilarides** [comment]
You can download it here: https://wetlandsint-my.sharepoint.com/:u:/g/personal/lammert_hilarides_wetlands_org/ER0GnDINnxJLl62ZMm9pzG8B8EYOJdPsoVQ4C181QQ5JlA?e=DMfsjh

The column "gid_0" has the ISO country code, please ignore the other columns with country codes

**Comment by dhakelila** [comment]
Thanks, Lammert, we'll take care next week!

**Comment by lhilarides** [comment]
@aagm : here's a new version with a fix for the overlapping country boundaries of Malaysia and Indonesia: 
https://wetlandsint-my.sharepoint.com/:u:/g/personal/lammert_hilarides_wetlands_org/EUgM0WdyhLZGl59TUba1F5MB7nBtXk2owefV8y7dofZDPA?e=wCsord

**Comment by aagm** [comment]
staging is currently updated with the new locations. So does the maps, that are using the new eez+gadm and wdpa
