### ISSUE TITLE
Mangrove Biodiversity Data

### ISSUE THREAD

**Issue by klongleywood** [Vizzuality/mangrove-atlas#330]
A table containing mangrove biodiversity data by country is attached. To start, this will be for a simple widget that displays the number of mangrove species, and lists each species
[Mangrove_Biodiversity.csv](https://github.com/Vizzuality/mangrove-atlas/files/7382354/Mangrove_Biodiversity.csv)
.

**Comment by klongleywood** [comment]
There also may be an opportunity to include data here on the types of species depending on mangroves if that is within scope. The assessments.csv is a list of all animal and plant species that have mangroves (either 1.7 - Forest - Subtropical/Tropical Mangrove Vegetation Above High Tide Level OR 12.7 - Marine Intertidal - Mangrove Submerged Roots) listed on their assessment (2000+). Then the countries.csv has the species names and countries they occur in. If you merge the spreadsheets, you will have all (at least as far as IUCN assessments) species that occur in mangroves by countries of occurrence. Then it will be possible to filter. (e.g., only threatened species, certain taxonomic groups (e.g., our 6 megafauna groups), etc.).
[assessments.csv](https://github.com/Vizzuality/mangrove-atlas/files/7637098/assessments.csv)
[countries.csv](https://github.com/Vizzuality/mangrove-atlas/files/7637099/countries.csv)

**Comment by klongleywood** [comment]
@dhakelila @tamaramegan Feedback on the widget design from today's call:

We like option 2 where the donut shape shows # of species according to their IUCN status. Do you have access to that dataset or do you need us to compile it for you? Easy to do on our end, just let us know. 

We're wondering if, for the global view, we could visualize the # of mangrove species by country either by making the EEZs different colors or coloring each mangrove area based on the number of species per country

**Comment by tamaramegan** [comment]
Hi  @klongleywood!
For you first question if you can compile the species according to IUCN status on your side it would be great!
For the second, I'll bring it up to the team in our next meeting to discuss.
Thank you!

**Comment by klongleywood** [comment]
Ok! We will compile -- thanks for the update!

**Comment by klongleywood** [comment]
@tamaramegan @dhakelila thanks for sending the template for the protected area data! Would you mind doing the same for the biodiversity data so we can fill it in appropriately?

**Comment by dhakelila** [comment]
Sure! As soon as we get it, we'll send it!

@tamaramegan, let's discuss when it can be ready. 

Thanks!

**Comment by AngelArcones** [comment]
@klongleywood The data model for the species data should remain unchained, with the same format as the Mangrove_biodiversity.csv file in the first message of this thread. We have already developed the pipeline to transform from that format to the one we will be using in the API.

It is important that countries names in the file match (when possible) the names we shared in the locations file ( 
[Country_location_id.csv](https://github.com/Vizzuality/mangrove-atlas/files/7971476/Country_location_id.csv) ).

**Comment by klongleywood** [comment]
Thanks @AngelArcones - we will work on making sure the country names are consistent, but how would you like us to include the IUCN status in that data scheme? The original csv I sent didn't contain that information.

**Comment by AngelArcones** [comment]
@klongleywood We can retrieve the IUCN status during the processing of the data, so there is no need to include it on the original file

**Comment by klongleywood** [comment]
@AngelArcones -- ok, so you don't need us to compile the IUCN statuses? Just want to confirm since earlier your team had requested that we do this and I have someone working on it.

**Comment by AngelArcones** [comment]
Yes, it is not necessary from your side anymore. We did requested that information initially, but upon developing the data processing pipeline for the widget, we are now able to retrieve that too.

**Comment by klongleywood** [comment]
@AngelArcones here is the updated mangrove biodiversity list. I've highlighted the countries in our list that don't have an entry in the list you provided (because this data was based on an earlier mangrove map). I can provide a copy where I've deleted these, if you like, but I thought I'd keep them in there just in case the new baseline data includes any of those missing countries. Otherwise, the country names should match. 

[Species_Binary_20220223.csv](https://github.com/Vizzuality/mangrove-atlas/files/8127143/Species_Binary_20220223.csv)

**Comment by AngelArcones** [comment]
@klongleywood I believe this was the approved design (instead of a list of names, which was the other option), but let us know if anything has changed.

![Screenshot 2022-03-07 at 18 37 19](https://user-images.githubusercontent.com/57727579/157087977-1af601a3-d006-469c-bfc6-e75af80fb62c.png)

**Comment by lhilarides** [comment]
Re-opening this as I can't find some of the data, at least not on the global level (country level doesn't display at all). The source data has 63 species, but in the staging environment I only see 44 species mentioned globally. One example is Camptostemon philippinense. This is an Endangered species and because there are so few endangered species, missing one will be noticed by visiting experts immediately

**Comment by klongleywood** [comment]
@lhilarides @dhakelila I'm also not seeing the data appear at the country level, but would like to do some ground-truthing of the total numbers before we release given the issues with the global summary. 

Also, in the staging app there are only 4 categories -- can we double check that there are no mangrove species that are considered data deficient or vulnerable?

We also need to add the following information to the info button:

Overview:  Species lists by country were compiled by the authors of the World Atlas of Mangroves (Spalding 2010) and verified by further expert and literature review. In 2022, hybrids were removed from the list, and the list was again cross checked against the IUCN Red List, and verified by a specialist group at IUCN. The status from the IUCN Red List was then assigned to each species. The number of threatened species reflects the number of endangered and critically endangered mangrove species. The data included are based on public literature and expert consultation and review; however, it cannot be assumed that species-level field verification has occurred consistently across every country or region, and may not incorporate temporal changes in species distribution. 

Year: 2022

References: Spalding, M. (2010). World atlas of mangroves. Routledge.  

IUCN. 2022. The IUCN Red List of Threatened Species. Version 2022-1. https://www.iucnredlist.org.

**Comment by dhakelila** [comment]
Thank you for reporting, we are trying to fix this.

**Comment by dhakelila** [comment]
@mluena info button is missing text, check message above from Kate.

**Comment by dhakelila** [comment]
@klongleywood , info button added. Please review and close the issue if everything looks good to you.
![Screenshot 2022-08-02 at 12 40 19](https://user-images.githubusercontent.com/6608294/182355724-cdfebe13-f12b-4146-8eea-18b436176f36.png)

**Comment by klongleywood** [comment]
Everything looks good except that the IUCN credit currently under License should be under reference instead. Under license we can put N/A since there is no data download here.

**Comment by dhakelila** [comment]
@mluena , can you take care of it?

**Comment by dhakelila** [comment]
@klongleywood latests changes done. Please, check and close issue if you consider the widget complete. 
Thanks! 

cc/ @lhilarides
