### ISSUE TITLE
Mangrove Restoration Potential

### ISSUE THREAD

**Issue by klongleywood** [Vizzuality/mangrove-atlas#331]
Clara and team, 

I've put the mangrove restoration data used in the app on Mapping Ocean Wealth in [this folder](https://tnc.box.com/s/8abiem7o8lyd9x1pvpe2yn2mdibgpcqk). Here, you'll also find a guide to the attribute fields. The one addition to the spatial data file is the Loss_Driver field. We'll want to add a description for the mangrove driver of loss for each country and typology unit. Otherwise, we can model the widget on the MOW tool: maps.oceanwealth.org/mangrove-restoration

As we discussed, this dataset is currently being updated to reflect the new mangrove extent, but the data will largely have the same structure as the attached, so you can use this to start mapping out the widget and identifying any issues.

**Comment by klongleywood** [comment]
@dhakelila @tamaramegan and cc @lhilarides 

An update on this dataset -- we expect to have the revised version by February. In the next version, we will not be including the People Protected ecosystem service metric, but the rest of the data structure should stay the same.

**Comment by klongleywood** [comment]
Another quick note as this widget gets developed - the default symbology for the map appearing on this site should be the map units symbolized by restoration score, rather than by typology type. I can clarify next week if need be

**Comment by dhakelila** [comment]
@mluena, @aagm  this is relevant when updating the restoration layer.
