### ISSUE TITLE
Alerts widget updates

### ISSUE THREAD

**Issue by dhakelila** [Vizzuality/mangrove-atlas#369]
Hi @lhilarides, just to let you know that everything is set on our end for you to update the Alerts widget. 
David Inga is working on the documentation so you can give it a try!

**Comment by lhilarides** [comment]
Managed to upload the full dataset this morning. @aagm has a few improvements to the documentation written, but (I think) not committed yet. After this the issue can be closed

**Comment by dhakelila** [comment]
@aagm , Are you done with the edits on the documentation?

**Comment by dhakelila** [comment]
@aagm please, add the link to the updated documentation

**Comment by dhakelila** [comment]
@lhilarides docs updated. https://github.com/Vizzuality/mangrove-atlas/tree/develop/cloud-functions
