### ISSUE TITLE
Legend in Mangrove Blue Carbon widget doesn't correspond to map layer

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#378]
The legend in the Blue Carbon widget does not correspond to the colors on the map. The map layer is good, the widget is wrong. Probably all that's needed is to switch the HTML codes of the colors. The color that is now used for the (700-1400) category should be used for the highest category

![image](https://user-images.githubusercontent.com/3919721/162638862-e58345c9-79c7-4973-a2f8-7e6f9ac83d3b.png)

**Comment by dhakelila** [comment]
@mluena , can you take a look?

**Comment by mluena** [comment]
This problem has been solved and is ready for deployment. Heroku has internal problems (it has been down for a few days already), this will be updated as soon as they fix it
