### ISSUE TITLE
on/off button in widget not activated when layer is disabled on the map

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#379]
When a layer is disabled on the map, the corresponding on/off button in the widget is not switched off. When you want to re-enable the layer you then first need to switch the widget button off before you're able to switch it on again.

![image](https://user-images.githubusercontent.com/3919721/162639087-823b517f-95b8-419d-9b96-76d7ccb78cb1.png)

**Comment by dhakelila** [comment]
@mluena , can you take a look?

**Comment by mluena** [comment]
This problem has been solved and is ready for deployment. Heroku has internal problems (it has been down for a few days already), this will be updated as soon as they fix it
