### ISSUE TITLE
Issue with reporting loss in Mangrove Net Change

### ISSUE THREAD

**Issue by klongleywood** [Vizzuality/mangrove-atlas#393]
@dhakelila and fyi @lhilarides 

Another issue caught using the training exercises -- I'm looking at the Mangrove Net Change widget for Mexico -- overall, the tool reports a loss from 1996 to 2016, but in the visual/graph, every year shows a gain. I can't capture it in the screenshot but if I hover, any loss values are null (they read NaN km2).  I'm seeing that bug in other countries too (Bangladesh). 

![image](https://user-images.githubusercontent.com/54109064/166057571-6c64431b-db44-4566-8b5b-34dd0e72cb90.png)

**Comment by mluena** [comment]
thanks for reporting it, I'll look into this today

**Comment by mluena** [comment]
Solved in staging and production
