### ISSUE TITLE
Mangrove Net Change bug: inconsistent layers showing

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#418]
Steps to reproduce:
1. Load the homepage
2. Zoom into any area with a lot of change (Guinea-Bissau, Niger Delta, Mahakkam Delta, etc.)
3. Switch on the Mangrove Net Change Layer
4. Change the end-year from 2016 to 2015
5. Change the end-year back to 2016 
6. All change polygons have now disappeared

In general the switching between start- and end-years seems to produce very random results after the first change

**Comment by dhakelila** [comment]
Done: https://www.loom.com/share/0d4de010c89b47648ef9e00bf3d0e607

**Comment by lhilarides** [comment]
Re-opened: instead of disappearing, the polygons do appear now but do not change when you select different years. See the two screenshots below, that show two distinct periods but the exact same gain/loss on the map:
![2022-07-22 14_03_36-Global Mangrove Watch — Mozilla Firefox](https://user-images.githubusercontent.com/3919721/180440183-dc23fa06-b25e-42ce-8f90-1c071f0b261a.png)
![2022-07-22 14_03_16-Global Mangrove Watch — Mozilla Firefox](https://user-images.githubusercontent.com/3919721/180440233-e2db9812-53ef-429f-83d9-4a60941d67a3.png)

**Comment by dhakelila** [comment]
@mluena

**Comment by dhakelila** [comment]
@klongleywood , @lhilarides this is ready for testing.

**Comment by lhilarides** [comment]
Closing this issue here and further tracking layer display in https://github.com/Vizzuality/mangrove-atlas/issues/421
