### ISSUE TITLE
Re-calculate the coastline coverage statistics for GMW v3.14

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#420]
Re-calculate the coastline coverage statistics for GMW v3.14. There should be existing scripts to do this (from Edward)

**Comment by aagm** [comment]
Hi Lammert! 
I am doing some QA over the numbers related mangrove coastal coverage as we have noted +-10% of difference from the v2 to v3 version, with the way I did the calculations. I think it could be a good topic to discuss tomorrow. i want to validate the methodology followed with you

**Comment by dhakelila** [comment]
New numbers are there. 
@lhilarides , can you write down your concerns with the costal length to Alicia can check into it?
