### ISSUE TITLE
Update mangrove biomass and height data to version 3

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#427]
New raster data for mangrove biomass and height based on GMW extent version 3 (as well as statistics), can be downloaded from:

https://www.dropbox.com/sh/ruk6m9btrkqb73b/AAC8lWSe7nOfDGzrapMR_uqRa?dl=0

I propose we use this dataset to build capacity with @klongleywood and myself to update datasets in the future
- ingestion in GEE
- create tilesets
- update country and site statistics

**Comment by dhakelila** [comment]
It seems this task doesn't below to the current scope. 

Lammert is proposing that Vizzuality only takes care of the tiles generation. As it is out of the scope, we'll check how long it might take, but we'll only do it if it takes a very few hours. I'll let you know. 
We can always create a contract amendment to include it. 

@lhilarides, @klongleywood, please, let me know if you agree.

**Comment by dhakelila** [comment]
Hey Lammert, this update was not included in the scope. Can we create an amendment to include it and all the potential updates and changes related to the new data?

**Comment by dhakelila** [comment]
Update from Lammert about the colors: 
Hi Alicia,

Thanks! You can find the intervals for mangrove biomass and height in this post on GitHub: https://github.com/Vizzuality/mangrove-atlas/issues/427#issuecomment-1188824852
Please do stick to the original colors on the website, the colors in the excel file are just for illustration.

**Comment by aagm** [comment]
Hi Lammert! 
We have realized that the data for the widget sent was incomplete. Let me explain, so far we need two different paraments across all locations:
* [x] The average height in the location. 
* [] The distribution of areas between the different height classes. 

On the statistics sent, we only have the data for **partial locations** (countries) and only the **average height** per location.

**Comment by lhilarides** [comment]
Hi Alicia, that distribution between the classes should also be there. I'm
currently on me phone so not easy to browse through the different issues
and link directly, but it's in the files with data relating to the
"donuts". I now realize that for height we used a bar instead of a donut,
but the data should be there

**Comment by aagm** [comment]
Confirmed, data can be found in this [issue](https://github.com/Vizzuality/mangrove-atlas/issues/460)

**Comment by dhakelila** [comment]
REady for revision

**Comment by lhilarides** [comment]
Two small issues I found:
1. The data that is displayed is the correct data for 2020, but the widget mentions the year 2016. Please change this to 2020
2. The colors of the buckets 5-10m and 10-15m seem to be exactly the same. Please change these in the legend as well as in the bar

![image](https://user-images.githubusercontent.com/3919721/189958179-f2ed922f-b037-43f7-83a1-bdb143664798.png)

**Comment by dhakelila** [comment]
Fixed
![Screenshot 2022-09-16 at 12 27 27](https://user-images.githubusercontent.com/6608294/190619038-4d6cee13-49fd-42d1-ba10-4de5657011a8.png)
