### ISSUE TITLE
Widgets re-calculation

### ISSUE THREAD

**Issue by dhakelila** [Vizzuality/mangrove-atlas#438]
After the update of the Extend data and the inclusion of the new WDPA, some of the widgets must be recalculated. Either to update the values or to include these new areas: Extent, Net change, biomass and height.

The Blue Carbon widget will also need recalculation, but as there will be an update on this dataset, soon (September) we'll wait to have that new data to get it done. 

Lammert will liaise with Pete to get those numbers ready, so Vizzuality only needs to update it on the project. 

Alicia will provide all the necessary information so Pete can run the scrips and provide the data in the correct format. 

A priori, the info needed is:
- Table structure expected for each of the widgets mentioned above. 
- Cleaned WDPA table. 
- Scrips from Ed as examples as Pete will run it in Python, so won't use them directly. 

@aagm, Can you provide the info described above? The sooner, the better.

The idea is to have all this data update ready and checked by the 26th of July but everything depends on when we get the numbers to be updated. 

Please, @lhilarides, correct or add any further info and let us know if there is something else needed from Pete.

**Comment by dhakelila** [comment]
From Lammert via email: 

Just a quick update that Pete can produce the statistics for the protected areas next week. I will send him the WDPA vectors I used for the protected area calculations. Those are based on the July 2022 update of the WDPA and have fixed geometries. To prevent confusion and version issues I will ask Alicia to use this same WDPA vectors to update the vector tiles.

@aagm FYI

**Comment by dhakelila** [comment]
@lhilarides , @klongleywood , @aagm 

Hi Lammert, I don't know why we would need to recalculate those tiles. 

Alicia sent you the WDPA data long ago for you to create those numbers, which you sent us and what we incorporated on Friday. 
So all that should match. 

Why do you think there is a need to recalculate the tiles? 
Have you used something different than what Alicia sent you to do your calculations? 

@aagm FYI

**Comment by aagm** [comment]
@lhilarides  I would also suggest doing a small sync with Pete in order to prepare a course of action for migrating the GEE scripts from Ed that are currently in javascript into this repo as python notebooks. Within the scope of recalculating the data.
