### ISSUE TITLE
Blue carbon widget note about incoming data

### ISSUE THREAD

**Issue by dhakelila** [Vizzuality/mangrove-atlas#440]
Hi @klongleywood , as discussed during our meeting, we'll include a note on the Blue Carbon widget to let the users know there is new data coming soon. 

Please, provide the text. :)

**Comment by lhilarides** [comment]
How about this:

"This information is based on an outdated GMW version. Please use for reference only while we are in the process of updating this to the latest GMW version 3."

Maybe show it in a light italic font just above the normal widget text, so it stands out a bit but doesn't distract too much

**Comment by dhakelila** [comment]
Sounds good to me!

**Comment by dhakelila** [comment]
Done: 
<img width="435" alt="Screenshot 2022-07-21 at 17 29 23" src="https://user-images.githubusercontent.com/6608294/180419289-0ed734e9-c486-424c-af4e-7eb1ede3bcce.png">

**Comment by dhakelila** [comment]
Done:
<img width="579" alt="Screenshot 2022-07-22 at 12 24 11" src="https://user-images.githubusercontent.com/6608294/180419878-eff2f853-f376-4321-a591-b73c574cedaf.png">
