### ISSUE TITLE
[Bug]: Mangrove Blue Carbon donut doesn't correspond to legend

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#442]
In the Blue Carbon widget the colors of the donut are not in the same order as in the legend. See below, these two color should be switched. Please make sure the percentages to correspond to the correct classed.

![image](https://user-images.githubusercontent.com/3919721/179488604-caefa049-f181-4669-980f-cfbf5e9cbd8e.png)

**Comment by dhakelila** [comment]
<img width="568" alt="Screenshot 2022-07-22 at 12 19 54" src="https://user-images.githubusercontent.com/6608294/180419193-a67407b5-9656-461c-9b68-629a425d0e44.png">
Fixed!
