### ISSUE TITLE
[Bug]: widgets keep reloading when zoomed in to country level

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#443]
On staging.globalmangrovewatch.org , when you click on a country boundary and zoom in to the country, the widgets continuously reload (every 2 seconds). They should load once and then be static. 

### Steps To Reproduce:
1. staging environment
2. using latest firefox and chrome on windows 10 pro 64bit
3. open site, click on a country boundary (tested with Nigeria and Benin)
4. see screenshot below

![image](https://user-images.githubusercontent.com/3919721/179755981-a7160de0-811a-4378-85e7-471c44630b28.png)

**Comment by dhakelila** [comment]
Hi Lammert, I agree we need to solved this asap but I'm not sure this will be ready for the release. We'll do our best.

**Comment by dhakelila** [comment]
Fixed! https://www.loom.com/share/4b07bbd4eed3408b840a36181e1d25ab
