### ISSUE TITLE
Categories, layers and display levels

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#444]
In the current staging environment the not all layers are displayed in the correct categories and at the correct levels. I have made an overview of each category, corresponding layers and the correct display levels (global, country, site) in the attachment. Please follow this overview for the release and let me know if there's any questions!
[GMW - categories - layers and levels.xlsx](https://github.com/Vizzuality/mangrove-atlas/files/9141382/GMW.-.categories.-.layers.and.levels.xlsx)

**Comment by lhilarides** [comment]
I still see many differences between the overview file and the staging environment. Can you do another check? 

For example the mangrove habitat change widget still appears (should be disabled entirely) and the mangrove species widget doesn't appear on the country level

**Comment by dhakelila** [comment]
@mluena , can you check?

**Comment by mluena** [comment]
Sure! About the habitat change, I'll remove it, the spreadsheet is showing "no" to every location but the release column was marked as yes so I wasn't very sure, sorry about that. Regarding species, I can see it at the country level, if you are missing some countries maybe we need to look into data, example [here](http://staging.globalmangrovewatch.org/country/VNM?map=eyJiYXNlbWFwIjoibGlnaHQiLCJ2aWV3cG9ydCI6eyJsYXRpdHVkZSI6MTUuMzkyMjc0NTU1MTQ0MjI0LCJsb25naXR1ZGUiOjEwMy42MzIxMjQ1MDUyOTQ4NCwiem9vbSI6NS40MDIxNjk3MjU4NjM1NzgsImJlYXJpbmciOjAsInBpdGNoIjowfX0%3D&widgets=eyJoaWdobGlnaHRlZF9wbGFjZXMiOnsiaXNDb2xsYXBzZWQiOnRydWUsImlzQWN0aXZlIjpmYWxzZX0sIm1hbmdyb3ZlX2V4dGVudCI6eyJpc0NvbGxhcHNlZCI6dHJ1ZSwiaXNBY3RpdmUiOnRydWV9LCJtYW5ncm92ZV9jb3ZlcmFnZSI6eyJpc0NvbGxhcHNlZCI6dHJ1ZSwiaXNBY3RpdmUiOmZhbHNlfSwibWFuZ3JvdmVfbmV0X2NoYW5nZSI6eyJpc0NvbGxhcHNlZCI6dHJ1ZSwiaXNBY3RpdmUiOmZhbHNlfSwibWFuZ3JvdmVfaW52ZXN0bWVudF9wb3RlbnRpYWwiOnsiaXNDb2xsYXBzZWQiOnRydWUsImlzQWN0aXZlIjpmYWxzZX0sIm1hbmdyb3ZlX2FsZXJ0cyI6eyJpc0NvbGxhcHNlZCI6dHJ1ZSwiaXNBY3RpdmUiOmZhbHNlfSwibWFuZ3JvdmVfc3BlY2llcyI6eyJpc0NvbGxhcHNlZCI6dHJ1ZSwiaXNBY3RpdmUiOmZhbHNlfSwibWFuZ3JvdmVfYmx1ZV9jYXJib24iOnsiaXNDb2xsYXBzZWQiOnRydWUsImlzQWN0aXZlIjpmYWxzZX0sIm1hbmdyb3ZlX3Byb3RlY3Rpb24iOnsiaXNDb2xsYXBzZWQiOnRydWUsImlzQWN0aXZlIjpmYWxzZX0sIm1hbmdyb3ZlX2hlaWdodCI6eyJpc0NvbGxhcHNlZCI6dHJ1ZSwiaXNBY3RpdmUiOmZhbHNlfSwibWFuZ3JvdmVfYmlvbWFzcyI6eyJpc0NvbGxhcHNlZCI6dHJ1ZSwiaXNBY3RpdmUiOmZhbHNlfSwiY29uc2VydmF0aW9uX2hvdHNwb3RzIjp7ImlzQ29sbGFwc2VkIjp0cnVlLCJpc0FjdGl2ZSI6ZmFsc2V9LCJtYW5ncm92ZV9hY3Rpdml0eSI6eyJpc0NvbGxhcHNlZCI6dHJ1ZSwiaXNBY3RpdmUiOmZhbHNlfSwibWFuZ3JvdmVfcmVzdG9yYXRpb24iOnsiaXNDb2xsYXBzZWQiOnRydWUsImlzQWN0aXZlIjpmYWxzZX19).
I am going to double check the rest again, if you spot any other mistake let me know

**Comment by lhilarides** [comment]
Thanks for checking @mluena . The issue seems to be with the data, most countries are missing (I checked 7 but 6 did not have data). See also issue #330 , comment: https://github.com/Vizzuality/mangrove-atlas/issues/330#issuecomment-1191905936

**Comment by lhilarides** [comment]
> I am assuming the widgets are shown in aoi and wdpa if it's shown at the country level
This is not always true, for example both the species and protected areas widgets can't be shown for WDPA's and AOI's. There doesn't exist any data on this level. The spreadsheet has the correct levels for displaying each widget

**Comment by dhakelila** [comment]
@mluena biomass and height widgets missing at wordwide. Can you check?

**Comment by lhilarides** [comment]
1. Mangrove Species and Mangrove Protection are now displayed in the wrong category (distribution and change instead of restoration and conservation). Problem at World and Country, but not at Site level.
2. At site level (Rufiji for example) the widgets in the Distribution and Change category are all collapsed on opening
3. Mangrove Aboveground Biomass and Mangrove Height are missing from the "Ecosystem Services" category.

Probably good to do another check vs this excel file:
[GMW.-.categories.-.layers.and.levels(1).xlsx](https://github.com/Vizzuality/mangrove-atlas/files/9184363/GMW.-.categories.-.layers.and.levels.1.xlsx)

**Comment by lhilarides** [comment]
I just did a full check of the staging environment and there's still quite some things to fix. I've tried to capture everything in the screenshot below. @dhakelila can you prioritise this and double check before marking fixed?

![image](https://user-images.githubusercontent.com/3919721/189935830-7f33304d-a241-4c81-a9ed-746529214813.png)

**Comment by lhilarides** [comment]
@klongleywood could you indicate whether we need to display the widgets marked with a "?" at the global level? Thanks!

**Comment by klongleywood** [comment]
@lhilarides -- none at a global level -- thanks!

**Comment by dhakelila** [comment]
Thanks for the table. I think it's 100% clear now. We are prioritizing to get all the widgets right first and we'll review all this early next week.

**Comment by lhilarides** [comment]
Production: on the country level, the Mangrove Height widget does not appear under "All datasets". Please note that when you first navigate to the Ecosystem Services category and then to All datasets, it does appear.

**Comment by dhakelila** [comment]
Hi Lammert, thank you for reporting. This is now fixed, we also found it yesterday. 
I'd recommend reviewing this task at the very end of the project as things might change during the coming days due to the new changes to including the "on-the-fly" analysis.
