### ISSUE TITLE
DATA UPDATE: WDPA areas Above Ground Biomass and Height

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#452]
This file has the mean Above Ground Biomass (column agb_avg) and mean Height data (hchm_avg) for the WDPA areas. The first column has the WDPAID for each individual area

Please note: this file also has a column agb_tot for total biomass, but we do not use that (yet)
[protected_agb_hgt_summarised_base_stats.xlsx](https://github.com/Vizzuality/mangrove-atlas/files/9158915/protected_agb_hgt_summarised_base_stats.xlsx)

**Comment by dhakelila** [comment]
Ready for revision
