### ISSUE TITLE
DATA UPDATE: Mangrove Biomass and Mangrove Height donuts - countries and WDPA 

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#460]
Attached the statistics to update the "donuts" in the widgets for mangrove biomass and mangrove height.
Biomass donuts countries: 
[gmw_v3_agb_summary_bounds.xlsx](https://github.com/Vizzuality/mangrove-atlas/files/9160626/gmw_v3_agb_summary_bounds.xlsx)

Biomass donuts WDPA:
[gmw_v3_agb_protect_area_bounds.xlsx](https://github.com/Vizzuality/mangrove-atlas/files/9160627/gmw_v3_agb_protect_area_bounds.xlsx)

Height donuts countries:
[gmw_v3_hchm_summary_bounds.xlsx](https://github.com/Vizzuality/mangrove-atlas/files/9160646/gmw_v3_hchm_summary_bounds.xlsx)

Height donuts WDPA:
[gmw_v3_hgt_protect_area_bounds.xlsx](https://github.com/Vizzuality/mangrove-atlas/files/9160652/gmw_v3_hgt_protect_area_bounds.xlsx)

**Comment by dhakelila** [comment]
Hi @lhilarides, we don't feel comfortable adding this before the release. We'll do it next week.

**Comment by lhilarides** [comment]
Hi Clara, I don't get it, this is the data we agreed to calculate for you on Monday? If this data is not in then we can't show the biomass and the height widgets and layers at all

**Comment by dhakelila** [comment]
Yes, I know, but we got the data yesterday, and we haven't enough time to upload it. We are preparing everything for the release as Monday is a bank holiday here in Spain.
We can hide the widgets, though.

**Comment by dhakelila** [comment]
@aagm , please, add this data as soon as you can.

**Comment by dhakelila** [comment]
@lhilarides , there is another issue with Biomass and Height data (https://github.com/Vizzuality/mangrove-atlas/issues/452)

Which is the difference? Is all the data complementary?

Please, use a single thread to send related data so we keep everything in the same place. Thanks!

**Comment by dhakelila** [comment]
Widgets updated. Generating map layers

**Comment by dhakelila** [comment]
Widgets and maps ready for your revision
