### ISSUE TITLE
[Bug]: clicking on a country no longer zooms in to that country on the map

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#461]
### Current Behavior:
When you load the homepage and click a country the map no longer zooms in to that country

### Expected Behavior:
The map zooms in to the country you click

### Steps To Reproduce:
1. staging environment
2. start at home page
3. click on Nigeria (or any other country)
4. widget data loads for country but on the map nothing happens....

**Comment by dhakelila** [comment]
Fixed: https://www.loom.com/share/9a98216f86b14001addd160e72192055
