### ISSUE TITLE
Species and Protected areas widget ready for your revision

### ISSUE THREAD

**Issue by dhakelila** [Vizzuality/mangrove-atlas#463]
@lhilarides, @klongleywood Species and Protected areas widget are ready for your revision. 
Please, let us know if you are ok with those, and we'll deploy them to the production site.

**Comment by lhilarides** [comment]
I like the looks of the Species widget. I just did some quick testing and it's probably still under development a bit, so some of this might have been addressed already. Anyway, here's some feedback

1. The widget doesn't appear on the Country level
2.  please use the official colors of IUCN for the legend. The colors used now have different meanings than the official ones so that may be very confusing (e.g. red = endangered instead of near threatened; grey = data deficient instead of threatened)
![content_categories_chart_global_v3](https://user-images.githubusercontent.com/3919721/180300738-7e6f1d96-f731-409e-8d34-57318b5fd53c.jpg)
2. The dropdown list for the "least concern" category is could be a bit longer before the scroll starts and it's too narrow now (some speciesnames take 2 lines to display)

**Comment by lhilarides** [comment]
Feedback on the Protected Areas widget:
1. the donut goes "counter-clockwise", whereas donuts in other widgets go clockwise. Would be good to be consistent in this
2. please add the switch for ha/km2 like we have in all widgets with areas
3. could you add a small image of a protected area as a legend? To make the connection to what people see on the map?
![2022-07-21 21_44_59-Global Mangrove Watch — Mozilla Firefox](https://user-images.githubusercontent.com/3919721/180304533-7e02ab1f-ceca-4967-bd9b-08f26ba90e61.png)
4. Please update the widget text to:
Top: Mangroves found in protected areas in <country> in **2022** represented <00000><ha/km2> out of a total <00000><ha/km2>.

Below the donut: Note: This represents the proportion of mangroves known to occur within protected areas. The level and the effectiveness of protection of these mangroves however are unknown.

This last bit of text can be in Italics, the same as the Note on the Blue Carbon widget. 

Kate and I will work on the references and info text

**Comment by dhakelila** [comment]
@lhilarides two questions about the Protected areas feedback:

- _the donut goes "counter-clockwise", whereas donuts in other widgets go clockwise. It would be good to be consistent in this_ → This widget only has 2 categories. The order is irrelevant, isn't it? 

_could you add a small image of a protected area as a legend? To make the connection to what people see on the map?_ --> Understood the need to have a reference to link the map and the widget, but not sure that is the best solution. WE are gonna use the same colour for the layer and the widget for now and will check with the designers.

**Comment by lhilarides** [comment]
These remaining two points are not urgent, so fine to postpone until after the 26th and check with the designers first

**Comment by dhakelila** [comment]
Great! Are you ok then if we publish the Protected areas widget in Production already?

**Comment by lhilarides** [comment]
> Great! Are you ok then if we publish the Protected areas widget in Production already?

Yes, that would be fine for me. Please do take into account issue #444 as well before deploying

**Comment by dhakelila** [comment]
Hey @lhilarides the only pending point in this issue is the following one: 

the donut goes "counter-clockwise", whereas donuts in other widgets go clockwise. It would be good to be consistent in this → This widget only has 2 categories. The order is irrelevant, isn't it?


It's not clear to us what is needed. Can you clarify?

**Comment by dhakelila** [comment]
@lhilarides please, take a look at the question above. I think that is no longer relevant, but please, confirm.

**Comment by klongleywood** [comment]
@dhakelila @lhilarides  Can we check on the statistics showing up in the donut chart for Protected Areas? If you hover over the gray part of the donut chart, the area number that shows up is the same number as the total area of mangrove for the country. Shouldn't it be showing the unprotected mangrove area (i.e. total area - area of mangrove within protected area?)

**Comment by dhakelila** [comment]
@klongleywood this is ready for your revision. Please, close the task if it looks good. 
![Screenshot 2022-09-12 at 22 08 07](https://user-images.githubusercontent.com/6608294/189747733-e687681f-3440-40c3-bfba-5efce3a3605e.png)

Let's track the info button updates in the [thread I created for that purpose](https://github.com/Vizzuality/mangrove-atlas/issues/525).

**Comment by lhilarides** [comment]
On the global level this works fine now! However, the widget is not displayed on a country level any longer so I cannot check that now. Will do this as soon as https://github.com/Vizzuality/mangrove-atlas/issues/444 has been fixed

**Comment by dhakelila** [comment]
![Screenshot 2022-09-16 at 12 24 29](https://user-images.githubusercontent.com/6608294/190618477-7d5123dd-f270-4413-9db5-4b9e5f795bff.png)

Working. Attached example for Nigeria
