### ISSUE TITLE
[Bug]: bottom widget is collapsed by default in certain categories

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#472]
1. Open staging environment
2. Click on the "restoration and conservation" or the "ecosystem services" category
3. This is what you see (the bottom widget should be expanded by default)

![image](https://user-images.githubusercontent.com/3919721/180420527-bc4de1b1-9bd4-400f-b9d5-60f36a94d353.png)

**Comment by dhakelila** [comment]
@mluena see an example: https://www.loom.com/share/89ce15798dd1414892ed68ee37445fad

**Comment by lhilarides** [comment]
Just checked, still needs to be done
