### ISSUE TITLE
Add legend back to Mangrove Net Change widget

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#474]
When the gross gain and gross loss were removed from graph in the Mangrove Net Change widget, also the legend was removed. However, we still do need the legend to explain what the map layer shows. I suggest to use the following:
green rectangle = mangrove gain
red rectangle = mangrove loss

black line = mangrove net change

**Comment by dhakelila** [comment]
@mluena I think this went away when we removed the areas from the chart. 
Can you manually include the legend on the widget as @lhilarides proposed?

**Comment by mluena** [comment]
Yes the legend consumes the info from the chart, once you remove that info, the legend goes away. I'll fix it

**Comment by lhilarides** [comment]
Looks great, thanks! One final request: could you change the text in the legend to "Net change" instead of just "net"?

![image](https://user-images.githubusercontent.com/3919721/180859263-a782a9ac-e59f-44ff-ac48-f7f453086f93.png)

**Comment by dhakelila** [comment]
![Screenshot 2022-09-12 at 22 27 18](https://user-images.githubusercontent.com/6608294/189752347-f5496965-7b44-40cb-8003-9533a4c022b0.png)

Ready for revision

**Comment by lhilarides** [comment]
Fixed, closing issue
