### ISSUE TITLE
[Bug]: Expand / Collapse all widgets button is missing from the Climate and Policy category

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#482]
1. Production environment
2. Go to the Climate and Policy category
3. The Expand / Collapse all widgets button is missing here

![image](https://user-images.githubusercontent.com/3919721/180868012-32fa02e9-ec7c-46a6-898c-5bed040d85ab.png)

**Comment by mluena** [comment]
The button was hidden for categories that have just one widget as there is no option to expand / collapse. To make this more obvious, I put the button back and disabled it for this cases
