### ISSUE TITLE
Info buttons missing

### ISSUE THREAD

**Issue by dhakelila** [Vizzuality/mangrove-atlas#497]
Hi @klongleywood , we got some texts for some of the widgets but we are still missing some of the texts. Can you send those through? 

These are the widgets we are missing the info for:
- Mangrove Restoration 
- Mangrove Protection

**Comment by klongleywood** [comment]
@lhilarides can you take care of the protection info text when you get back? 
I'll draft text for the restoration widget and run it by Tom.

**Comment by dhakelila** [comment]
Follow up: https://github.com/Vizzuality/mangrove-atlas/issues/525
