### ISSUE TITLE
Mangrove investment potential ready for revision

### ISSUE THREAD

**Issue by dhakelila** [Vizzuality/mangrove-atlas#505]
Mangrove investment potential widget is ready for you to review [in staging](http://staging.globalmangrovewatch.org/?map=eyJiYXNlbWFwIjoibGlnaHQiLCJ2aWV3cG9ydCI6eyJsYXRpdHVkZSI6MjAuMDAwMDAwMDAwMDAwMDA0LCJsb25naXR1ZGUiOjAsInpvb20iOjIsImJlYXJpbmciOjAsInBpdGNoIjowfX0%3D&widgets=eyJoaWdobGlnaHRlZF9wbGFjZXMiOnsiaXNDb2xsYXBzZWQiOnRydWUsImlzQWN0aXZlIjpmYWxzZX0sIm1hbmdyb3ZlX2V4dGVudCI6eyJpc0NvbGxhcHNlZCI6dHJ1ZSwiaXNBY3RpdmUiOmZhbHNlfSwibWFuZ3JvdmVfY292ZXJhZ2UiOnsiaXNDb2xsYXBzZWQiOnRydWUsImlzQWN0aXZlIjpmYWxzZX0sIm1hbmdyb3ZlX25ldF9jaGFuZ2UiOnsiaXNDb2xsYXBzZWQiOnRydWUsImlzQWN0aXZlIjpmYWxzZX0sIm1hbmdyb3ZlX2ludmVzdG1lbnRfcG90ZW50aWFsIjp7ImlzQ29sbGFwc2VkIjp0cnVlLCJpc0FjdGl2ZSI6ZmFsc2V9LCJtYW5ncm92ZV9hbGVydHMiOnsiaXNDb2xsYXBzZWQiOnRydWUsImlzQWN0aXZlIjpmYWxzZX0sIm1hbmdyb3ZlX3NwZWNpZXMiOnsiaXNDb2xsYXBzZWQiOnRydWUsImlzQWN0aXZlIjpmYWxzZX0sIm1hbmdyb3ZlX2JsdWVfY2FyYm9uIjp7ImlzQ29sbGFwc2VkIjp0cnVlLCJpc0FjdGl2ZSI6ZmFsc2V9LCJtYW5ncm92ZV9wcm90ZWN0aW9uIjp7ImlzQ29sbGFwc2VkIjp0cnVlLCJpc0FjdGl2ZSI6ZmFsc2V9LCJtYW5ncm92ZV9oZWlnaHQiOnsiaXNDb2xsYXBzZWQiOnRydWUsImlzQWN0aXZlIjpmYWxzZX0sIm1hbmdyb3ZlX2Jpb21hc3MiOnsiaXNDb2xsYXBzZWQiOnRydWUsImlzQWN0aXZlIjpmYWxzZX0sImNvbnNlcnZhdGlvbl9ob3RzcG90cyI6eyJpc0NvbGxhcHNlZCI6dHJ1ZSwiaXNBY3RpdmUiOmZhbHNlfSwibWFuZ3JvdmVfYWN0aXZpdHkiOnsiaXNDb2xsYXBzZWQiOnRydWUsImlzQWN0aXZlIjpmYWxzZX0sIm1hbmdyb3ZlX3Jlc3RvcmF0aW9uIjp7ImlzQ29sbGFwc2VkIjp0cnVlLCJpc0FjdGl2ZSI6ZmFsc2V9LCJtYW5ncm92ZV9lbWlzc2lvbnNfbWl0aWdhdGlvbiI6eyJpc0NvbGxhcHNlZCI6dHJ1ZSwiaXNBY3RpdmUiOmZhbHNlfX0%3D).
![Screenshot 2022-08-05 at 12 56 36](https://user-images.githubusercontent.com/6608294/183063499-2d52502c-7c69-4bc8-883d-464a445f6284.png)

**Comment by klongleywood** [comment]
Not sure if anyone will see this as I know everyone is on break, but this has disappeared from staging. I was planning on doing a demo for testing for our climate and policy group on Wednesday. If there's any way to get this easily re-deployed that would be appreciated.

**Comment by klongleywood** [comment]
@mluena and fyi @dhakelila and @lhilarides -- I still am not able to see this widget on staging and I would really like to be able to review this widget with our climate and policy group. Can you give me a sense of when this will be back up and running? Thank you!

**Comment by dhakelila** [comment]
Hi @klongleywood , I see this widget was included in the branch María and Ángel prepared with[ "Policy and Climate" widgets](https://mangrove-atlas-git-feature-international-sta-aff369-vizzuality1.vercel.app/country/TZA?map=eyJiYXNlbWFwIjoibGlnaHQiLCJ2aWV3cG9ydCI6eyJsYXRpdHVkZSI6LTYuMzk0MDI0ODE0MjQ5MTkxLCJsb25naXR1ZGUiOjI0Ljk4OTc4MDQ1NjI2MTk4Niwiem9vbSI6NC4yMjA1MTY5NTY4NzUxMzUsImJlYXJpbmciOjAsInBpdGNoIjowfX0%3D). 
Remember to select an specific location to see it.

**Comment by dhakelila** [comment]
Closing this thread as new feedback arrived in a new thread
