### ISSUE TITLE
[Bug]: Translation not working consistently

### ISSUE THREAD

**Issue by klongleywood** [Vizzuality/mangrove-atlas#520]
Selecting French or Spanish only translates the text of the widget partially. See below for an example:

![Incomplete French translation](https://user-images.githubusercontent.com/54109064/189134422-3f8e062f-6620-4f62-999e-30246156d899.JPG)

FYI @dhakelila @lhilarides

**Comment by klongleywood** [comment]
@lhilarides see above, do you have access to the Transifex dashboard?

**Comment by lhilarides** [comment]
I assigned this one to myself. We're working with WWF and Cambridge Uni on getting translations done.
