### ISSUE TITLE
Info buttons update

### ISSUE THREAD

**Issue by dhakelila** [Vizzuality/mangrove-atlas#525]
@lhilarides , @klongleywood, I've seen in a couple of issues mentioning the need to update the info in the info button. Please, track all those cases under this issue, so we don't forget any of them. 

Start by creating here a list of widgets that needs this update and then, pass the text here.

**Comment by klongleywood** [comment]
- Mangrove habitat extent - update needed for 2020 data @lhilarides can you work on this one?
- Mangrove protection - @lhilarides 
- Mangrove restoration @klongleywood 
- Mangrove height, biomass, and blue carbon update for 2020 data @lhilarides

**Comment by lhilarides** [comment]
Mangrove Habitat Extent download button: https://zenodo.org/record/6894273

Mangrove Habitat Extent information window:
**Global extent of mangroves for select years from 1996 to 2020.**

**Overview:**
This layer depicts the global extent and change of mangrove forests in the years 1996, 2007 - 2010 and 2015 - 2020. The data set was generated within the framework of the Global Mangrove Watch (GMW) , an initiative convened  by Aberystwyth University, soloEO, The Nature Conservancy and Wetlands International.

The proportional length of coastline covered by mangroves was calculated by intersecting the mangrove extent, buffered by 200 m, with the Global Shoreline Vector dataset (Sayre, 2019) within each geometry. The percentage (%) covered was then calculated as the sum of the length of coastline occupied by mangrove habitat (km) divided by the total length of coastline (km) within the geometry multiplied by 100. Please note coverage calculations are still under validation.

The paper describing the mangrove extent and change dataset is available at:
https://doi.org/10.3390/rs14153657

The paper describing the Global Coastline Vector dataset:
https://doi.org/10.1080/1755876X.2018.1529714

**Date of content:**
1996, 2007, 2008, 2009, 2010, 2015, 2016, 2017, 2018, 2019, 2020

**License:**
CC-BY 4.0

**Comment by lhilarides** [comment]
### Mangrove Protection Widget
**Download button:**
- Spreadsheet: [insert url once table is uploaded somewhere]

**Overview**
This layer shows the area and proportion of mangroves in protected areas per country. The level of protection that protected ares afford to mangrove habitats varies, as does the degree to which they are effectively governed and managed.

The extent of mangroves found in protected areas was calculated using three datasets:
1. World Database on Protected Areas (July 2022)
2. Global Mangrove Watch v3.0 for the year 2020
3. Country and Exclusive Economic Zone boundaries by UNEP-WCMC.

The WDPA dataset was filtered for protected areas (PA_DEF = 1) excluding those with a "proposed" status (STATUS != Proposed). The remaining data was intersected with the Country-EEZ dataset and then dissolved by country. This dataset was used to clip the GMWv3.0 dataset and calculate the mangrove extent in protected areas. This number was divided by the total extent of mangroves for each country to get the proportions.

**Reference:**
GMWv3.0: Bunting et al 2022
WDPA: UNEP-WCMC and IUCN (2022), Protected Planet: The World Database on Protected Areas (WDPA) [Online], September 2022, Cambridge, UK: UNEP-WCMC and IUCN. Available at: www.protectedplanet.net.
Country-EEZ: not yet available

**Date of content:**
2020 (mangrove extent) / 2022 (protected areas)

**License:**
cc-by-4.0

**Comment by dhakelila** [comment]
Info added to Extent and Protection

**Comment by klongleywood** [comment]
We made a few small changes to the info button language for the climate and policy widgets:

**Mangrove International Status:**

Nationally Determined Contributions (NDCs) reflect a country’s proposed actions under the Paris Climate Agreement to cut emissions and adapt to climate change. Data used in this tool to describe a country’s NDC comes from Global Climate Watch (WRI 2022), or directly from the text of the country’s NDC. 

Information on whether a country’s NDC includes coastal and marine NBS (Nature-Based Solutions) comes from a policy brief ([Lecerf et al. 2021](https://ocean-climate.org/wp-content/uploads/2021/06/coastal-and-marine-ecosystem-2806.pdf)) developed in anticipation of the UNFCCC COP26 (United Nations Framework Convention on Climate Change Convention of the Parties, held in Glasgow in November 2021). NBS are actions to protect, sustainably manage and restore natural and modified ecosystems in ways that address societal challenges effectively and adaptively, to provide both human well-being and biodiversity benefits. In this context, mitigation measures aim to avoid and reduce emissions of GHGs into the atmosphere to prevent further warming. In the context of coastal and marine NBS, mitigation measures can include reducing loss of natural habitats that store carbon (e.g., mangroves and seagrasses), or restoring natural habitats that capture carbon.  Adaptation measures aim to alter behavior, systems, and ways of life to protect people, economies and the environment from climate change impact. In the context of coastal and marine NBS, these can include improve resilience of coastal ecosystems. Coastal and marine NBS provide important opportunities for responding to climate change and achieving national climate policy goals. The data presented here offer a chance to better understand where countries are already using coastal and marine NBS, and where there might be opportunities to enhance the use of NBS in future NDC revisions. 

The[ 2013 Supplement to the 2006 IPCC Guidelines for National Greenhouse Gas Inventories: Wetlands Supplement](https://www.ipcc-nggip.iges.or.jp/public/wetlands/) is a methodology report adopted by the IPCC (International Panel on Climate Change), which contains guidelines for countries on improving their inventorying and reporting of GHGs from wetlands (see Coastal Wetlands Chapter 4), with the goal of providing a pathway for countries to reduce agricultural emissions from peatlands and mangroves. 

[FRELs (Forest Reference Emission Level)](https://www.forestcarbonpartnership.org/forest-reference-emission-levels) is a benchmark for emissions exclusively from deforestation and forest degradation. Setting a FREL is a necessary first step for countries to benefit from REDD+ (Reducing Emissions from Deforestation and Forest Degradation). Mangroves, in some cases, are part of a FREL if included in the National Forest Definition. Each country is responsible for this definition based on national context. If mangroves are considered forests in the country, , they are eligible for inclusion in all  REDD+ activities, including but not limited to financing from market mechanisms or results-based payments.

**Carbon Market Potential**

Estimates of mangrove forest area that can qualify for blue carbon financing that is financially sustainable over 30 years, based on prices of $5/ton and $10/ton based on[ Zeng et al. (2021)](https://ap5.fas.nus.edu.sg/fass/geofd/zeng%20et%20al%202021%20return%20on%20investment%20mangrove%20blue%20carbon.pdf). These investible carbon areas are mangrove forests that can be protected through carbon financing. Areas of investible mangrove are defined as those under imminent threat of loss or decline if left unprotected by a conservation intervention. The estimate also accounts for carbon from above and below ground biomass, as well as soil carbon. Profitability of projects was based on average costs of project establishment and annual maintenance, weighted by the country’s GDP. Investible areas are rounded to the nearest 100. Estimates of mangroves in protected areas are based on the World Database of Protected Areas (July 2022). Calculations of remaining mangroves (i.e. mangroves that are not within protected areas and not considered investible) are based on GMW extent v 3.14.
 
The prices here are intended to be indicative to provide an understanding of the investability of a mangrove area. It is not intended to limit the price per ton of mangrove carbon, particularly as market prices rise for premium carbon units and high-quality blue carbon credits. These data can be used to better understand, at a national scale, the potential of blue carbon finance that can be used towards climate mitigation goals, including nationally determined contributions specified under the Paris Climate Agreement.

**Comment by dhakelila** [comment]
Carbon market updated in production. 
International status ready in staging for your approval. (https://github.com/Vizzuality/mangrove-atlas/issues/342)

**Comment by dhakelila** [comment]
As discussed during one of our last meetings, we'll update the year range of the Biomass andHeight widgets to show 1997-2020. Please, review the references in case they need to be updated. 
"_Global mangrove aboveground biomass density for selected years between 1997 and 2016"_
_"Global mangrove canopy height for selected years between 1997 and 2016"_
