### ISSUE TITLE
Mangrove Habitat Change

### ISSUE THREAD

**Issue by dhakelila** [Vizzuality/mangrove-atlas#528]
Hi @lhilarides , @klongleywood , do you remember the Mangrove Habitat Change widget? 
The one where we used to rank the countries. 

It was disabled long ago, and we are not sure if we should bring it back, but Maria found it in the categories spreadsheet. 

This is important because we should adapt this to the new data. 

Please, let us know.

**Comment by lhilarides** [comment]
Yes, since we have the new data, it would be a shame to not display it. The only change needed to the widget would be to remove the gain and loss so only the net change is shown.

**Comment by dhakelila** [comment]
Ok @lhilarides since this was out of the radar, we'll evaluate what is needed in terms of adapting to the new data and decided whether we can include this week's sprint. I'll let you know.

**Comment by dhakelila** [comment]
@lhilarides , @klongleywood the widget was included. It's already in production.

**Comment by lhilarides** [comment]
Hi Clara, can you disable it in production asap? The numbers that are shown are incorrect and the widget behaves weird (e.g. the top 5 completely changes depending on whether you show 5 or 10 countries in the list). Let's look at this in our next meeting

**Comment by dhakelila** [comment]
Widget disabled in production. Still showing in staging. 

I always see the same countries. 🤔
Alicia will review the numbers. 

![Screenshot 2022-09-20 at 12 02 09](https://user-images.githubusercontent.com/6608294/191229776-f763aaca-5028-435e-88fe-d2c3d66d3f24.png)
![Screenshot 2022-09-20 at 12 01 23](https://user-images.githubusercontent.com/6608294/191229782-f84697f3-22ce-4df8-a086-ea45dad0fb0d.png)

**Comment by aagm** [comment]
Hi Lammert, the data came from the same source as the net-change and extent widgets.

The ranking is calculated as the aggregation (sum) of the values of net change per year( _extent in y_ - _extent in y-1_) in the period the user selects for each country location. Then we do order desc and limit (5 or 10) depending on user selection.
This gave us the locations with the **greatest positive** cumulative change. 

One way to improve this is to rank it by the absolute extent value so we can incorporate both positive and negative cumulative changes.

**Comment by mluena** [comment]
Removed from prod and ready to be checked in staging, let me know if the
version in staging is good for production

**Comment by dhakelila** [comment]
Now there is a new version of this widget showing the absolute bigger net change. 
There are some style issues we need to adjust. 

And one question, @lhilarides, @klongleywood: 
If you see 1996-2020, all the values are negatives, so the vertical line (the axis) gets placed on the left. 
If you check 2016-2020, there are negative and positive values, so the bar is at the centre. 
Is that ok, or should we force the chart always to place the vertical axis in the middle? 

![Screenshot 2022-09-30 at 13 04 51](https://user-images.githubusercontent.com/6608294/193256542-17ca97fe-3cc5-4d1f-8e2d-76935b85375f.png)
