### ISSUE TITLE
Vizzuality logo

### ISSUE THREAD

**Issue by dhakelila** [Vizzuality/mangrove-atlas#530]
Hi @klongleywood , @lhilarides I realized Vizzuality logo is not on the website. Do you think we could add it along with the other logos on the about section? 

We could say: Designed by: Vizzuality. 

![Screenshot 2022-09-13 at 10 09 42](https://user-images.githubusercontent.com/6608294/189849014-fa8b7526-2246-445e-b378-83cd76d20992.png)

**Comment by dhakelila** [comment]
@lhilarides , @klongleywood, I'd like to drive your attention to this point. This is important for us. :)

**Comment by lhilarides** [comment]
Hi Clara! Yes, it would be fine by us to put that text + your logo there (below the donors section)

**Comment by dhakelila** [comment]
![Screenshot 2022-09-20 at 09 20 08](https://user-images.githubusercontent.com/6608294/191192783-46d83cf3-eb33-4f98-b874-730fa97235de.png)
