### ISSUE TITLE
Remove Areas of Interest

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#534]
Since we have now introduced many more protected areas I think we can completely ditch the concept of "Areas of Interest". I do like featuring some areas with images in the search interface so would like to keep that. This has absolutely no priority by the way

**Comment by dhakelila** [comment]
@lhilarides , I don't know if there is a specific action for us here. 

I understand you want to keep the highlighted areas in the search panel and I assume we don't want to remove the option to navigate to them by clicking on the map, so no sure what/if we need to do something in this sense.

**Comment by lhilarides** [comment]
The "area of interest" is a separate geometry now, so it is duplicative. I think all that needs to be done is:
1. link the "highlighted places" to the corresponding WDPA geometry
2. remove the areas of interest

**Comment by dhakelila** [comment]
https://docs.google.com/spreadsheets/d/1UHVH5NbSPx3OLEe-uDWEhewbx4LetiJPCPcaYLYv3cU/edit#gid=100294634
