### ISSUE TITLE
Mangrove Net Change Widget - dropdown too narrow when scrollbar appears

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#536]
The dropdown list of the mangrove net change is too narrow when the scrollbar appears, see below.

I would suggest to use the styled scrollbar that we also use for the mangrove species widget (see 2nd image) for consistency
![image](https://user-images.githubusercontent.com/3919721/189952365-c71d6b50-f5b8-4706-a863-2145320500c3.png)

![image](https://user-images.githubusercontent.com/3919721/189952704-b532e751-9e84-4b3c-bade-ca11c78cec9b.png)

**Comment by dhakelila** [comment]
@lhilarides it's working fine in Mac. Please, confirm it's working for you as well. :)
