### ISSUE TITLE
[Bug]: legend/layer order restoration and extent layer

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#546]
The order of the layers does not match the order of the legend items. In this case I think the restoration layer should be displayed on top in the map

![image](https://user-images.githubusercontent.com/3919721/190633803-a88f761c-e8b4-4b25-a048-5ee72f4f3279.png)

**Comment by dhakelila** [comment]
@lhilarides we agreed Extent layer will always be at the bottom. We already have a TODO for that.
