### ISSUE TITLE
Mangrove Extent: sorting of the years is reversed

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#548]
On staging the sorting of years has been reversed. In the rest of the site, the oldest year is on top (which is good!), but now in the extent widget the newest year is on top:

![image](https://user-images.githubusercontent.com/3919721/190638086-1132137f-dc9c-44af-b9a3-67514d8ae795.png)

**Comment by dhakelila** [comment]
Ready! 

![Screenshot 2022-09-27 at 22 38 50](https://user-images.githubusercontent.com/6608294/192630633-94afdd8c-2357-4227-9575-c5d36f04de3f.png)
