### ISSUE TITLE
[Bug]: multiple raster layers not displayed in the western hemisphere

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#549]
Staging environment:
The following layers are not displayed on the map anywhere west of Ghana and the dateline in the Pacific Ocean.
1. Mangrove net change
2. Mangrove height
3. Mangrove biomass

Here's Fiji, there are mangroves on both sides of the dateline, but no change/biomass/height layer is visible

![image](https://user-images.githubusercontent.com/3919721/190645249-9bb7e81f-40e1-4a43-91df-2799112a046d.png)

**Comment by dhakelila** [comment]
@lhilarides , we found the issue with the map layers.
It seems that we accidentally added a mask when exporting the layers from GEE so we got only part of the world.

Alicia is already generating the rest of the layers. It should be done by Tuesday. I'll keep you posted.

**Comment by dhakelila** [comment]
New layers there. 
![Screenshot 2022-09-19 at 09 58 17](https://user-images.githubusercontent.com/6608294/190973715-5366291f-dc05-4f07-ab80-9af1ffd3fb79.png)
![Screenshot 2022-09-19 at 09 58 09](https://user-images.githubusercontent.com/6608294/190973720-230bda6c-d688-470a-9e36-e82225dd3f11.png)
