### ISSUE TITLE
[Bug]: Regression bug issue 401 

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#555]
I noticed the cloud-functions had been updated, without merging the PR I created to fix issue #401 

I don't want to interfere in your commits/PR at this stage, so please apply the changes to the current codebase to make sure this issue remains fixed:

https://github.com/lhilarides/mangrove-atlas/commit/3834dfd2fb315661e43abd010fb6cbfed2474272

**Comment by aagm** [comment]
the issue should be [fixed here](https://github.com/Vizzuality/mangrove-atlas/pull/558)  and deployed in the Function already
