### ISSUE TITLE
Analysis feature ready! 

### ISSUE THREAD

**Issue by dhakelila** [Vizzuality/mangrove-atlas#590]
@lhilarides , @klongleywood  The analysis feature is ready for you to start testing in a new branch: 
https://mangrove-atlas-da08u0kmj-vizzuality1.vercel.app/

That branch is a bit behind staging, and you will see some issues that were reported and solved in the last week but we didn't fix those on that branch. Please, don't pay attention to anything different than the analysis feature. 

As Lammert has the event in Kenya, we decided not to push any changes to staging until Wednesday as we risk making it unstable. If you think we can keep working on staging, just let us know and we'll integrate everything into staging as soon as possible. 

There are minor interactivity issues to be solved and we'll take care of them during the next days. 
E.g: You can't give up drawing a polygon by pressing "esc", if you want to get back to the "countries" the pop-up shown is different than the rest of messages on the app, ...

@lhilarides , to progress with the feature and allow file uploading, we need to instal GDAL in the server. Can you make Alicia admin so she can install what she needs? 

Then, we need your help providing texts for the app.
1: On the Info pop-up, we'd like to explain the limitations of the feature given Google Cloud constraints. (This is the same issue you can experience in GFW. I'm attaching that example for reference)
![Screenshot 2022-09-30 at 13 38 36](https://user-images.githubusercontent.com/6608294/193261681-acaeae39-1087-4586-a808-40acf463d4ae.png)
![Screenshot 2022-09-30 at 13 40 35](https://user-images.githubusercontent.com/6608294/193262028-a04724d1-778e-4a1c-b8cb-282c2a4f310b.png)

2: When a geometry is too large, the analysis might fail, but Google Cloud will keep trying and then caching the result, so if the user keeps retrying, it will eventaully work. We'd like to inform users about this as well. Attaching GFW example.
![Screenshot 2022-09-30 at 13 44 25](https://user-images.githubusercontent.com/6608294/193262602-bcc49094-86c7-4076-97b0-a360efd0ce2b.png)
![Screenshot 2022-09-30 at 13 46 14](https://user-images.githubusercontent.com/6608294/193262905-b649255d-d0e2-4551-908c-775a5c70d7e0.png)

This is all, thank you for reading through the end of this long message. :)

**Comment by lhilarides** [comment]
I just tried it and it works really well, so great job all!

A few comments:
1. the net change widget is still missing
2. the AGB value on the blue carbon widget is always 0
3. we should look into the display of the change alerts. It currently shows the "global" change alerts layer, whereas the "national" layer provides a lot more detail, which is needed on a site level. However, for polygons that intersect with a country border this obviously won't work. Let's go over this in our next meeting!

**Comment by klongleywood** [comment]
Hi @dhakelila  -- Lammert and I just discussed the widgets that should show up when a custom area is selected, and we decided to show only the widgets that have selectable data (i.e., leave out widgets that only show country-level data like biodiversity, restoration, and any of the climate and policy stats other than blue carbon)

**Comment by dhakelila** [comment]
@klongleywood , @lhilarides we places a sentece to add the terms of service on the drawing tool, but I'm not sure if you want to add those. 

If you do, please, provide the text. If not, let us know and we'll simply remove that sentence. 

![Screenshot 2022-10-19 at 14 42 58](https://user-images.githubusercontent.com/6608294/196694233-12310722-2cc1-4bc7-8263-0f435b1bb752.png)
