### ISSUE TITLE
[Bug]: Mangrove habitat change widget flipped order of the top 10 countries

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#595]
See image below, the order of the countries has been reversed:
![image](https://user-images.githubusercontent.com/3919721/195847697-1e325b70-7470-436f-95d7-e69e0c4151c0.png)

**Comment by dhakelila** [comment]
@lhilarides , let me know if it works fine for you know. It seems to work fine for me. 
![Screenshot 2022-11-14 at 09 55 07](https://user-images.githubusercontent.com/6608294/201617150-1d68f36d-66d6-49f4-ab62-2d77c65f4f29.png)
