### ISSUE TITLE
[Bug]: Mangrove Net Change widget broken

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#596]
Production environment. The mangrove net change widget no longer displays any values for the change. Instead it shows NaN (not a number) 

![image](https://user-images.githubusercontent.com/3919721/196112025-0ad43887-48d0-43fd-a46a-fb5f894420e5.png)

**Comment by dhakelila** [comment]
Fixed and ready for you to check. 
![Screenshot 2022-11-14 at 09 57 13](https://user-images.githubusercontent.com/6608294/201617610-5a9c37fe-3b86-4ff5-987d-eab114e6434f.png)
