### ISSUE TITLE
[Bug]: Mangrove extent always displayed on top instead of on the bottom

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#602]
The mangrove extent layer should always be displayed as the bottom layer (it also used to). It now seems to be displayed always on top
![image](https://user-images.githubusercontent.com/3919721/197509676-b93f3ab2-e425-4df3-99f5-8162ecf63cdd.png)
This is just one example, but it goes for all layers

This is the production environment by the way

**Comment by mluena** [comment]
I'm currently in production and I can't reproduce this but I'll keep digging into it

**Comment by dhakelila** [comment]
![Screenshot 2022-11-14 at 09 58 28](https://user-images.githubusercontent.com/6608294/201617855-8482278c-cafc-47b8-bce4-5cb6638f02c1.png)

This seems to work as expected for me. Please, check

**Comment by lhilarides** [comment]
Still an issue, this is a screenshot of the staging environment on Windows 10 pro, Firefox 106 after a refresh.

![image](https://user-images.githubusercontent.com/3919721/202157844-77476466-79fa-4532-8b81-1c72b5901ed2.png)

**Comment by dhakelila** [comment]
@mluena it seems to be a bug with firefox and I still see it wrong there.

**Comment by dhakelila** [comment]
Ready for revision
