### ISSUE TITLE
[Bug]: Clicking on a country/protected-area from the search takes you to the "Custom area" menu

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#611]
Staging environment. Steps to reproduce:
1. Load homepage
2. Click search (magnifying glass)
3. Click any country / protected-area

Result: 
![image](https://user-images.githubusercontent.com/3919721/199953892-13640943-5778-4168-8875-5019610fdb09.png)

Result should be that you're taken to the area selected. If you click the Magnifying glass again you are taken to the correct area

**Comment by dhakelila** [comment]
https://www.loom.com/share/20084aa2dbe74503bbe3ff7a551c05d8

**Comment by dhakelila** [comment]
PS: @mluena , this only happens at the very beginning. If I navigate a bit and then select a location, it works fine. It only happens if I try to select a location at the very beginning.

**Comment by dhakelila** [comment]
Ready for testing
