### ISSUE TITLE
[Bug]: Mangrove height widget legend 

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#612]
The legend used to be displayed on top of the graph, instead of over it. This only seems to be a problem at the global level, as on country and protected area level it is displayed fine
![image](https://user-images.githubusercontent.com/3919721/199965847-19678354-909f-403e-b147-6a05a169aa77.png)

(This is Firefox on Windows 10)

**Comment by dhakelila** [comment]
@mluena it showing propoerly for me and Kate, so it might be Firefox.

**Comment by lhilarides** [comment]
It's also in Chrome, but only the widget that's displayed in the category "Restoration & Conservation"

**Comment by dhakelila** [comment]
![Screenshot 2022-11-16 at 17 48 16](https://user-images.githubusercontent.com/6608294/202242446-8114a2c7-b8ba-4dd0-a45d-3976229186de.png)

Ready for testing

**Comment by dhakelila** [comment]
@lhilarides I'd liek you to check this one since it was working fine for me. I checked on Firefox as well and it seems to be working fine, but still. 
![Screenshot 2022-11-18 at 15 03 37](https://user-images.githubusercontent.com/6608294/202722673-b8e0386e-e700-4d7c-b20c-39ed8db7d8e7.png)
