### ISSUE TITLE
[Bug]: Incorrect numbers in Mangrove Habitat Change widget

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#613]
Staging environment:

The numbers displayed in the Mangrove Habitat Change widget are not always correct. For example when you select a year different then 1996 as the start year:

![image](https://user-images.githubusercontent.com/3919721/199967197-7f057bb7-df46-49ec-a471-f80a48cb3b26.png)

This should say 781 km2 (you can check the numbers in the Mangrove Habitat Extent Widget on the country level)

**Comment by dhakelila** [comment]
It seems only 2007 is off. It seems to be taken the numbers of the previous year (1996)

**Comment by klongleywood** [comment]
I'm getting incorrect numbers with other years besides 2007. in the Australia net change widget 2008 - 2020 shows a decrease of 148; in the mangrove habitat change the value is showing up as -243 for that time range.

**Comment by dhakelila** [comment]
Hey! There seems to be 2 issues here. 
The one flagged by Lammert wich we are looking at. And the one flagged by Kate which we are not able to reproduce as as far as we can tell, numbers are correct. Could you give us more details, @klongleywood ?

Looking at Australia, we get: 
Extent 2008: 10,319.56 km²
Extent 2020: 10,170.81 km²
Decrease in mangrove net change widget: 148.75 km²

![Screenshot 2022-11-14 at 15 31 55](https://user-images.githubusercontent.com/6608294/201686228-678e3df8-b93e-4ee7-8312-3172aae316e7.png)

![Screenshot 2022-11-14 at 15 32 10](https://user-images.githubusercontent.com/6608294/201686227-bb0de6d3-7f23-4fdd-bf1f-fadca033a5de.png)

**Comment by klongleywood** [comment]
Ok, here are the steps to recreate (just to clarify this is staging not production). 

When the geography is set to Worldwide, in the Mangrove Habitat Change widget (i.e. the list of geographies by the amount of change), I set the year range from 2008 - 2020. Hover over the entry for Australia (this is the second entry from the top). It says that the change is -283. 

Then, if I select Australia from the geography search bar and navigate to the Mangrove Net Change widget and set the date range from 2008 - 2020, it gives a net change of -148.7. 

Hopefully that helps but happy to demo when we talk Friday.

**Comment by dhakelila** [comment]
Ok @klongleywood , I see what you mean now. Thanks!

**Comment by dhakelila** [comment]
@lhilarides , @klongleywood both issues flagged above are solved. 
1- Incorrect values for 2007.
2- Incorrect values for some countries. Example of Australia. 
![Screenshot 2022-11-18 at 12 20 21](https://user-images.githubusercontent.com/6608294/202693967-b57446cd-3701-4c4a-b8a8-20cfe3e5f745.png)
![Screenshot 2022-11-18 at 12 18 00](https://user-images.githubusercontent.com/6608294/202693970-1ac764d3-27bc-4d92-bd0d-ad09387f2aa6.png)
