### ISSUE TITLE
Hovering in Carbon Market Potential

### ISSUE THREAD

**Issue by klongleywood** [Vizzuality/mangrove-atlas#615]
The function in the Carbon Market Potential widget where you hover over the donut to see the value of the slice doesn't work consistently. Especially when the slice is relatively small, nothing shows up in the hover. Example for Cuba the only numbers that I can get to show up when I hover are the areas of mangrove in protected areas.

**Comment by dhakelila** [comment]
The tooltip has been improved. Please, let us know.
