### ISSUE TITLE
Add convening partners logo to main menu

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#616]
Same image as on the "About the GMW" page

**Comment by dhakelila** [comment]
Do you mean adding these: 
![Screenshot 2022-11-14 at 11 02 13](https://user-images.githubusercontent.com/6608294/201631855-6a798e34-30f4-4f91-a76e-d0bfd079c3d7.png)

Here: 
![Screenshot 2022-11-14 at 11 02 41](https://user-images.githubusercontent.com/6608294/201631958-a39b1394-9612-40d6-9050-eac35485a848.png)

**Comment by lhilarides** [comment]
Hi Clara, Yes, between the "Resources" link and the GMA logo, with a bit of whitespace.
