### ISSUE TITLE
Vertical scrollbar display on different widgets

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#620]
This was mentioned in previous issues, but not fixed yet. The vertical scrollbar in the habitat extent and net change widgets overlap with the values displayed. In the species widget there is a solution for this, by styling the vertical scrollbar. Styling the scrollbar consistently across all widgets would fix the issue and make it look better. See both styles below:

![image](https://user-images.githubusercontent.com/3919721/202159981-2702001a-312c-4097-9d7e-e4784cf27a1d.png)

**Comment by dhakelila** [comment]
![Screenshot 2022-11-18 at 12 23 14](https://user-images.githubusercontent.com/6608294/202694415-9d92fb85-fbba-49eb-8add-c318f6374658.png)
