### ISSUE TITLE
Missing thousand separator for numbers in the net change widget

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#621]
As in other widgets, the number in the net change widget should have the thousand separator:
![image](https://user-images.githubusercontent.com/3919721/202161056-17100bb8-c13e-4e8e-bf00-ebda97f1a9a6.png)

**Comment by dhakelila** [comment]
![Screenshot 2022-11-18 at 12 21 34](https://user-images.githubusercontent.com/6608294/202694141-14dd125b-8548-40a0-881d-7d0003e3f8b8.png)
