### ISSUE TITLE
Download window for net change widget

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#623]
1. The version linked to says v2, but is v3. Please change the text v2 into v3
2. It says here it's a link to gain and loss, but the data that is linked to only contains extent. Do we have the gain/loss data available separately @aagm ? 

![image](https://user-images.githubusercontent.com/3919721/202165083-b8a9e1cc-fdc5-4b80-a755-3b8c89e0f130.png)

**Comment by dhakelila** [comment]
@lhilarides , to your second question, we don't have the gain and loss data in a way they can be easily shared. 
The links were updated to show the v3 version, but those are the extent info, not the gain and loss. 

Options from Alicia: 
- Keep links changing the description.
- Use the same links as we have in "Habitat extent" widget, as it is the same data. 
- REmove the download from this widget altogether.

**Comment by lhilarides** [comment]
Let's copy the information from the extent widget download. Simple and
consistent

**Comment by dhakelila** [comment]
Done
![Screenshot 2022-11-18 at 13 23 23](https://user-images.githubusercontent.com/6608294/202704235-9556ff24-100e-481c-890c-ff916665af92.png)
