### ISSUE TITLE
Custom area: after doing a calculation there's no straighforward way to go back to the categories

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#632]
After doing a custom area calculation there's no straighforward way to go back to the categories, see the image below. If you click on one of the categories in the area outlined in red, nothing happens. One solution would be to display the warning that you're discarding the custom area, i.e. the same warning message that is displayed when you click on the "World" icon.

![image](https://user-images.githubusercontent.com/3919721/202747973-5f03fd0f-47c0-4d78-86fa-b5fb1993338e.png)

**Comment by dhakelila** [comment]
To enable the categories again you should navigate to a location different than custom.

**Comment by dhakelila** [comment]
@mluena just change the pointer. Right now the "hand" stays and it's confusing.
