### ISSUE TITLE
Restoration Typology Unit Tool Tip Hover

### ISSUE THREAD

**Issue by klongleywood** [Vizzuality/mangrove-atlas#635]
In the Restoration Widget, I'm trying to access the tool tip feature that allows me to hover over or click on a typology unit to show the restoration attributes of the individual unit. Nothing happens when I hover, and if I click on the unit on the map, the page reloads as a blank screen. In staging using Chrome. 

@dhakelila FYI

**Comment by dhakelila** [comment]
@klongleywood this bug was introduced with the work that SparkGeo recently submitted. We are working on it, and it should be fixed soon.

**Comment by dhakelila** [comment]
Ready for QC

**Comment by klongleywood** [comment]
This is working now but another issue has emerged! After I click on a typology unit, let's say I want to go to another country. I click in the country search field, and the search panel comes up momentarily but then disappears. In Chrome.

**Comment by dhakelila** [comment]
PS: I've seen the new thread. Let's close this issue and continue in the other one.
