### ISSUE TITLE
Can no longer share URL without losing settings

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#638]
We used to be able to share the URL with other users, so that the new user ends up on the same location and with the same layers enabled as the original user. This mostly still works, but there seem to be two things that go wrong now (at least with Firefox on Windows):
1. The category is lost and the new user defaults to the "Distribution and Change" category. This way the widgets and map layers no longer relate to each other (i.e. users see widgets with missing layers and/or layers with missing widgets)
2. The Mangrove Habitat Extent layer is not shown on the map, although the widget toggle is still switched on

**Comment by dhakelila** [comment]
It also happens to me in Chrome.

**Comment by dhakelila** [comment]
Ready for testing
