### ISSUE TITLE
Site defaults to mobile view on 1920x1080 display when windows desktop scaling is set at 150%

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#642]
Site defaults to mobile view on 1920x1080 displays when windows display settings are scaled at 150%. Four out of the ten people I trained today had this setting (the default is 125%), so it seems to be quite common. I think it has something to do with there not being enough vertical space available when fontsizes are 150%

**Comment by dhakelila** [comment]
@lhilarides , can you check now? 
The mediaqueries where set in a way that it would apply for those sizes to allow users to see the navigation bar before it has it scroll. Now that the sidebar has the scroll, we changed it again and it shouldn't happen again.
