### ISSUE TITLE
Clicking on Geography search doesn't work

### ISSUE THREAD

**Issue by klongleywood** [Vizzuality/mangrove-atlas#646]
In Staging, if I click on the area where I normally would select my geography from the dropdown menu, the dropdown menu appears momentarily and then disappears. Currently, the only way to get the data for a specific geography is to click on it on the map (Chrome)

**Comment by dhakelila** [comment]
It's funny as it seems to work for me:  https://www.loom.com/share/1607e29df5e4432f95045f074ce4ecfb
