### ISSUE TITLE
Mangrove emissions mitigation fields are switched

### ISSUE THREAD

**Issue by klongleywood** [Vizzuality/mangrove-atlas#647]
In staging, I believe that the fields that are feeding into the mangrove related interventions in the Mangrove Emissions Mitigation widget are reversed.

**Comment by dhakelila** [comment]
@AngelArcones can you check?

**Comment by AngelArcones** [comment]
@klongleywood I've checked the data at different stages of the process (original data, input data for the API, data shown on the platform) and as far as I've seen all the fields are showing the correct values for the countries and worldwide. Perhaps you can provide any example where you've seen some mismatch or odd value?

**Comment by klongleywood** [comment]
@AngelArcones  so sorry, you are right, that was my mistake. That said, I need to provide you with updated values for the restoration column based on the new data that came in for the restoration widget. I will work on updating that spreadsheet today.
