### ISSUE TITLE
Custom Area: calculations in Blue Carbon widget do not add up

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#683]
The sum of the Above Ground Biomass and Soil Organic Carbon is not the same as the total value. Either the total value or the SOC value is wrong

![image](https://user-images.githubusercontent.com/3919721/214043912-51182026-aa7f-438f-82b8-e9f0c027c660.png)

**Comment by lhilarides** [comment]
Please note that in case that it's the total value that is wrong, then it is incorrectly displayed in the text as well as in the donut.

**Comment by mluena** [comment]
I am not sure if the calculations are wrong or if the problem is just the format. I remember removing decimals from de ring chart, I put them back.
