### ISSUE TITLE
Mobile view css quirks on Android

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#686]
Overall, the mobile view works fantastic on an iPhone! On Android, using Chrome, there are 2 small issues:

1. The width of the interface in general seems to be too wide. On an iPhone it's exactly 100% of the width available, but on different Android phones (default Chrome browser) you have to scroll horizontally to see the map icon at the bottom right
2. In the map view, the map div does not use the full height available, as a results you see bits of widgets sticking out from under it.

**Comment by lhilarides** [comment]
Forgot to attach a screenshot:
![image](https://user-images.githubusercontent.com/3919721/214073619-7789a6ee-4bee-4caf-bc1e-306dfc49516d.png)

**Comment by mluena** [comment]
I am not able to replicate this is any device, I've tried with all browsers possible. Any more info that you could add?
