### ISSUE TITLE
Drivers of Change

### ISSUE THREAD

**Issue by dhakelila** [Vizzuality/mangrove-atlas#700]
Hi, @klongleywood , I see in the data tracking doc that the Drivers of change data is ready. 
Could you please send it or explain to us how to grab it from the Restoration dataset?

**Comment by klongleywood** [comment]
Hi @AngelArcones and @dhakelila.  

From the Vizz country stats data, you can pull the primary loss driver for the country from the column called "Driver" from the Vizz_Country_Stat csv provided with the restoration data.  I'm checking with Tom to see if we can use the numbers from Columns N, O, and P in some sort of infographic for that widget, but I need clarification on what they represent. I'll get back to you on that

On the map, the display should be the typological units (the same ones used in the Restoration dataset) using the attribute called Driver. There are 5 different drivers so they can each be symbolized by a different color.

**Comment by klongleywood** [comment]
@AngelArcones and @dhakelila and fyi @lhilarides 

I just talked to Tom and he suggested a slightly different approach to this that includes using the original drivers of change data. I'll be in touch in the next few days with an updated source dataset, but this suggestion actually simplifies the overall design.

**Comment by klongleywood** [comment]
Hi @AngelArcones -- this is a good question. My initial feeling is that we might not want to provide these data at the global scale for the reasons you stated, but let me verify this on our data team call on Friday. I'll let you know then!

**Comment by klongleywood** [comment]
@larranz-vizz I like it! @lhilarides what do you think?

Also, @AngelArcones confirming that we don't need this summarized at the global scale

**Comment by lhilarides** [comment]
Same here, good to go

**Comment by lhilarides** [comment]
Text for the Drivers of Change widget info button:

- Overview: This dataset provides estimates of the extent of mangrove loss, land cover change, and its anthropogenic or climatic drivers in three time periods: 2000-2005, 2005-2010, and 2010-2016. Landsat-based Normalized Difference Vegetation Index (NDVI) anomalies were used to determine loss extent in each period. The drivers of mangrove loss were determined by examining land cover changes using a random forest machine learning technique that considered change from mangrove to wet soil, dry soil, and water at each loss pixel. A series of decision trees used several global-scale land-use datasets to identify the ultimate driver of the mangrove loss. Loss drivers include commodity production (agriculture, aquaculture), settlement, erosion, extreme climatic events, and non-productive conversion. Maps of loss extent per period, mangrove land cover changes, and loss drivers are provided for each of 39 mangrove holding nations.

- Reference 1 (paper): [Goldberg, L.; Lagomasino, D.; Thomas, N.; Fatoyinbo, T. Global declines in human-driven mangrove loss. Glob. Chang. Biol. 2020, 26, 5844–5855](https://doi.org/10.1111/gcb.15275)
- Reference 2 (data): [Goldberg, L., D. Lagomasino, N. Thomas, and T. Fatoyinbo. 2022. Global Mangrove Loss Extent, Land Cover Change, and Loss Drivers, 2000-2016. ORNL DAAC, Oak Ridge, Tennessee, USA.](https://daac.ornl.gov/cgi-bin/dsviewer.pl?ds_id=1768)
- Reference 3 (more info): [more information](https://www.mangrovelossdrivers.app/):

- Date of content: 2000 - 2016

- License: [EOSDIS Data Use Policy](https://earthdata.nasa.gov/earth-observation-data/data-use-policy)
