### ISSUE TITLE
BUG in statistics for WDPA areas

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#707]
The statistics for WDPA areas are off by a factor of 100. The number should be 100x smaller. It seems to be a front-end problem. The numbers for countries and custom areas are displayed correctly.
![image](https://user-images.githubusercontent.com/3919721/232612442-fc6099d8-4e52-4ac6-856b-4ee9376aa37b.png)

**Comment by dhakelila** [comment]
On it!
