### ISSUE TITLE
Species distribution

### ISSUE THREAD

**Issue by larranz-vizz** [Vizzuality/mangrove-atlas#720]
Hello, @lhilarides and @klongleywood:

I have made a design at the [country](https://www.figma.com/proto/GJCx8yGfx6JERPuxlpG3nK/Mangrove-Watch-%5BInternal%5D?page-id=0%3A1&node-id=2110-16900&viewport=278%2C-1543%2C0.13&scaling=min-zoom&starting-point-node-id=31%3A2370&show-proto-sidebar=1) and [worldwide](https://www.figma.com/proto/GJCx8yGfx6JERPuxlpG3nK/Mangrove-Watch-%5BInternal%5D?page-id=0%3A1&node-id=2110-16363&viewport=278%2C-1543%2C0.13&scaling=min-zoom&starting-point-node-id=31%3A2370) level.

The map is a rough mockup I've made with software that doesn't allow using the real basemap style, so you will see it is slightly different from what it will be. But it helps to see how the choropleth layer will look based on our current data. I have lowered the opacity so the other data can be readable, but some adjustments could be made when we implement it and see it in a real context.

If I'm correct, you mentioned showing worldwide information at the country level (at least, I have done this way in my previous sketches). However, showing the number of species in each country along with an indicator in the legend would be a more effective way. Please let us know if you agree with our approach or if you have any further suggestions.

On the other hand, we suggest dividing the content of this widget into two cards. This way, the choropleth won't be mixed with the threatened chart, and the information in both parts will be more precise. You can look at the [proposal here](https://www.figma.com/proto/GJCx8yGfx6JERPuxlpG3nK/Mangrove-Watch-%5BInternal%5D?page-id=2162%3A17879&node-id=2162-18577&viewport=1346%2C910%2C1&scaling=min-zoom).

Many thanks!

**Comment by lhilarides** [comment]
I really like the way you've done this. Good to go  as far as I'm concerned 👍

**Comment by klongleywood** [comment]
Agreed :)

**Comment by klongleywood** [comment]
@larranz-vizz can we add an info button to the species location by country widget?  it can read: 

Species lists by country were compiled by the authors of the World Atlas of Mangroves (Spalding 2010) and verified by further expert and literature review. In 2022, hybrids were removed from the list, and the list was again cross checked against the IUCN Red List, and verified by a specialist group at IUCN. The data included are based on public literature and expert consultation and review; however, it cannot be assumed that species-level field verification has occurred consistently across every country or region, and may not incorporate temporal changes in species distribution.

Reference:
Spalding, M. (2010). World atlas of mangroves. Routledge. 

Date of content:
2022

License:
N/A

**Comment by klongleywood** [comment]
Yes, and can we have it here too?

![image](https://github.com/Vizzuality/mangrove-atlas/assets/54109064/6c1249a4-4c26-42b5-a55b-d85cec7ae542)

**Comment by larranz-vizz** [comment]
Yes, I think we can add the info button next to the toggle as in the rest of the widgets. Am I right @mluena?

FYI @dhakelila
