### ISSUE TITLE
Restoration widget with fisheries

### ISSUE THREAD

**Issue by larranz-vizz** [Vizzuality/mangrove-atlas#722]
Hello @lhilarides and @klongleywood,

I have a [proposal for the fisheries graph](https://www.figma.com/proto/GJCx8yGfx6JERPuxlpG3nK/Mangrove-Watch-%5BInternal%5D?page-id=2221%3A16433&node-id=2221-16581&viewport=1367%2C1370%2C0.95&scaling=min-zoom). As discussed in the last meeting; we are not adding the comparison between species but the amount. So, to make the information more visual, we have used the icons. The color will be taken from the other charts in the widget, and in the cases when the amount is 0, the icon appears disabled.

(I'm sharing the entire widget so you can see it in context).

Many thanks!

**Comment by klongleywood** [comment]
I like it!

**Comment by lhilarides** [comment]
Looks good. OK to implement like this 😁
