### ISSUE TITLE
Mangrove protection

### ISSUE THREAD

**Issue by larranz-vizz** [Vizzuality/mangrove-atlas#726]
Hi @lhilarides and @klongleywood,

I have a design for mangrove protection. Again, we suggest splitting the information into two pieces. Still, in this case, the compared mangrove area protected in different countries will be **a contextual layer** instead of a widget.

This is for consistency with the other widgets because, in any of them, we are showing just a legend of a layer; we always show some chart or sentence with additional data.

The behavior of the contextual layer will be the same as we defined before: these layers could be activated from the map settings section and certain widgets **as recommendations** (this is an example of the second way).

You can take a look here:
https://user-images.githubusercontent.com/131164193/236000399-ec102f9a-1619-4702-b99d-19b53b19c484.mov

Thank you!

**Comment by lhilarides** [comment]
Hi Lidia! I like this design and the color scheme, but I am wondering if it would not be possible to use (almost) the same approach as for the Blue Carbon widget, as follows:
1. Integrate the legend from the separate widget in the main widget
2. Show the global % protected as is
3. Integrate the toggle in the main widget

If I visualise it in my head it should work, but I'm open to being wrong :)

**Comment by larranz-vizz** [comment]
Hi, @lhilarides! Ok, let me know when you have discussed it.

Just replying to your comment about integrating the color scheme as the legend of the widget. Actually, it could be confusing for the users because the chart will behave differently than in the other widgets. They could expect the different colors to be categories.

**Comment by larranz-vizz** [comment]
Hi @lhilarides,

Clara told me you finally decided to use the same approach as the Blue Carbon widget. This is how the design looks:
- [country level](https://www.figma.com/proto/GJCx8yGfx6JERPuxlpG3nK/Mangrove-Watch-%5BInternal%5D?page-id=0%3A1&type=design&node-id=2010-15463&viewport=1087%2C-1776%2C0.25&scaling=min-zoom&starting-point-node-id=2010%3A15463&show-proto-sidebar=1)
- [worldwide](https://www.figma.com/proto/GJCx8yGfx6JERPuxlpG3nK/Mangrove-Watch-%5BInternal%5D?page-id=0%3A1&type=design&node-id=2688-22894&viewport=1087%2C-1776%2C0.25&scaling=min-zoom&starting-point-node-id=2688%3A22894&show-proto-sidebar=1)

Let us know if you are ok with it. Many thanks!

**Comment by lhilarides** [comment]
Looks good! OK with me
