### ISSUE TITLE
Mangrove Fishers

### ISSUE THREAD

**Issue by klongleywood** [Vizzuality/mangrove-atlas#732]
@dhakelila and fyi @lhilarides 

While we're waiting to hear the status of the fisheries enhancement model, I can share the results of the fishing pressure/fishers who rely on mangroves model. The spatial data can be found here: https://tnc.box.com/s/bm5q9jr4ztr0ujakd36jl8elgy5x56ij

Fish_pres is the dataset we'll want to display on the map. The units are fishers per km2 per year

The corresponding stats by country are in the attached table. 
[Mangrove_Fishers_Vizz.xlsx](https://github.com/Vizzuality/mangrove-atlas/files/11423954/Mangrove_Fishers_Vizz.xlsx)
The statistics I included are: 

Column B: percentage SSF mangrove fishers (in other words, the percentage of small scale fishers which were identified as mangrove fishers)
Column C: Median fishing pressure (fisher days per km2 per year)
Column D: Range of fisher days per km2 per year

I think the most important stat to display is the statistic from Column C, but if there was a way to incorporate the range somehow that would be helpful. The % statistic is potentially less important but if we find ourselves in a situation where we don't get the fisheries enhancement data, maybe we could include that instead. 

Open to other thoughts!

**Comment by dhakelila** [comment]
@AngelArcones , Kate is sharing provisional data for fisheries. She will have a chat with her team on Friday and we'll get more info after.

**Comment by AngelArcones** [comment]
@dhakelila @klongleywood Thanks! I'll look into possibilities on how to display this data.

**Comment by dhakelila** [comment]
@AngelArcones , clarification about the data shared: The data shared is not going to change. We can work with it. 

There is another dataset missing for this widget, but that, we are not sure about when might arrive.

**Comment by dhakelila** [comment]
Please, follow this conversation on https://github.com/Vizzuality/mangrove-atlas/issues/770
