### ISSUE TITLE
QA staging: 2 dropdown lists issues

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#839]
Dropdown lists in widgets have two new issues:
1. The dropdown lists expand when hovered over, but not when they're clicked. They should expand/collapse at least when clicked and I'm fine when they also expand on hover
2. Dropdown lists seem to have lost their scrollbars. It looks nice, but when using a mouse without a scrollwheel, there's no way to scroll through the list.
![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/4a894605-782a-42b5-8396-c771dfb7b64a)

**Comment by dhakelila** [comment]
Fixed: https://www.loom.com/share/a1067de4e8554bb0930d65f5d8dbef1e
