### ISSUE TITLE
QA Staging: National Dashboards (esp. Bahamas)

### ISSUE THREAD

**Issue by klongleywood** [Vizzuality/mangrove-atlas#855]
The Bahamas National Dashboard is showing the mangrove extent for other areas of the Caribbean but not the Bahamas. 

For all of the national dashboards, I think we need to have headers for the stats or else they don't necessarily make sense to the user. For example, over TNC, there should be a header called Source, over 2021, Year, over 5km2, Extent, etc...

There is too much space between the number 5 and the unit, and we shouldn't have the Habitat_Extent_Area as the header here. 

![image](https://github.com/Vizzuality/mangrove-atlas/assets/54109064/a405db10-00d2-4cf7-a998-6e1fb48d8719)

**Comment by dhakelila** [comment]
Fixed.

![Screenshot 2023-07-18 at 16 15 22](https://github.com/Vizzuality/mangrove-atlas/assets/6608294/35892a63-3f07-4b5b-9a4d-45a28623ea53)



https://mangrove-atlas-git-develop-v2-vizzuality1.vercel.app/country/TZA?category=%22all_datasets%22&active=[%22mangrove_restoration_sites%22,%22mangrove_habitat_extent%22]&bounds=[[16.465080730732723,-15.74927665043127],[44.04342461554728,3.135194047422786]]
