### ISSUE TITLE
QA Staging: Coastal Protection

### ISSUE THREAD

**Issue by klongleywood** [Vizzuality/mangrove-atlas#860]
A few issues with this widget (fyi @dhakelila and @lhilarides)

- Nothing changes on the map when the layer is turned on
- The text in the area panel (In Australia, mangroves are expected to protect 58.80 km2 during a average annual storm) needs to be copied down to the text in the population and stock panels. Note that for annual, the article should be an not a. 
- Round the decimal places in the area panel
- Use comma separators for thousands (mostly applies for population

**Comment by klongleywood** [comment]
Thanks! But one more fix -- km2 is only used in the first panel.  So, right now, the sentence in the second panel reads In Australia, mangroves are expected to protect 59,832 **km2** during a average annual storm, but it should be individuals. Similarly, in the third panel it reads:  In Australia, mangroves are expected to protect 792M **km2** during a average annual storm . but it should read $792M...

**Comment by dhakelila** [comment]
@lhilarides , @klongleywood , changes requested have been applied. 

Also, the scale for the map now changes for each scenario. So it considers all the values for all the countries for one scenario. I'd like to get your thoughts on this.

**Comment by klongleywood** [comment]
Hi @dhakelila I'm not sure I see what the change is but maybe we can review on Monday. One change I am still not seeing has to do with the decimal rounding. We don't want any decimal places in the Area panel. Thanks!

**Comment by dhakelila** [comment]
@klongleywood , I think this ticket is outdated now as we clarified that removing the decimal places was only for people. 

Let me know if we should do any changes on the widget. It is now live.

**Comment by klongleywood** [comment]
Agreed we can close this -- the decimal places are fine for area
