### ISSUE TITLE
QA staging: styling and sorting in monthly planet layers

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#869]
Dropdown list with months should be slightly wider, so every month is on a single line, and also sorted from recent months at the top to older months at the bottom

![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/35746958-c62e-4035-a38c-87b148f9da72)

**Comment by dhakelila** [comment]
Fixed

<img width="512" alt="Screenshot 2023-07-14 at 12 22 17" src="https://github.com/Vizzuality/mangrove-atlas/assets/6608294/021eebe1-f2a6-4f26-b60e-47b2c2e5120e">

**Comment by mluena** [comment]
Closing this issue as dropdown styles have been unified in this last phase.
![Screenshot 2024-02-14 at 18 01 08](https://github.com/Vizzuality/mangrove-atlas/assets/33252015/eaa7918a-bc25-4738-9edf-c1a72a0b14eb)
