### ISSUE TITLE
Add download link to the Mangrove alerts widget

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#884]
This was a small loose end. Please add this download link for the Mangrove Alerts:

https://storage.googleapis.com/mangrove_atlas/deforestation-alerts/Downloads/gmw_alerts_latest.gpkg

**Comment by dhakelila** [comment]
![Screenshot 2023-07-18 at 16 32 53](https://github.com/Vizzuality/mangrove-atlas/assets/6608294/06735d92-7e47-4fd7-aaca-5053adfd5b96)
Ready in staging
