### ISSUE TITLE
Planet labs layer

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#932]
The resolution of the Planet satellite background layer is very low. See below an image comparing the native 5m resolution with what is displayed on globalmangrovewatch

![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/fbc069fd-ace0-45a8-bde3-32abd1551391)

**Comment by mluena** [comment]
I've increased the max zoom level to improve the resolution

**Comment by lhilarides** [comment]
Works perfect now, closing this one
