### ISSUE TITLE
News: small issues

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#946]
1. When hovering over the new "News" button in the main navigation, the cursor doesn't change. It is clickable, but it doesn't look like that to the user
2. When a News item is open, the "Back to news" does not go back to the news item list, but closes the news completely
3. It would be nice to also show the tag(s) when a news item is open. Right now they're only showed in the news list

**Comment by mluena** [comment]
Hio @lhilarides, I fixed the issues, let me know if you need anything else or if it's ready to deploy to prod

**Comment by klongleywood** [comment]
Tested and confirmed QC
