### ISSUE TITLE
Alerts - scrollbar on firefox

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#947]
I'm not sure if this is a regression, because I thought this had been fixed, but in the current production and staging environment, the scrollbar of the Alerts widget is too wide (the monthly dropdown), causing the text to be garbled. Setting the CSS property of scrollbar-width to thin could do the trick. This is an issue on Firefox only by the way

**Comment by mluena** [comment]
I can´t replicate this, is still happening?
