### ISSUE TITLE
Mangrove Extent and Mangrove Net Change widgets: changing years doesn't change the map layers being displayed

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#955]
When I change the value of "year" in the widgets Mangrove Extent or Mangrove Net Change, for example from 2020 to 2007) nothing happens on the map and the same layer keeps being displayed. It's an issue on Firefox, Chrome and Edge on windows 10. This is quite urgent as it's one of the most used functions

Here's an example of an area with lots of change that makes replication easy: https://www.globalmangrovewatch.org/country/IDN?bounds=[[117.33943168403187,2.990685835238395],[117.60648901637467,3.188308456485032]]&active=[%22mangrove_net_change%22,%22mangrove_habitat_extent%22]

**Comment by mluena** [comment]
I'll look at it now

**Comment by mluena** [comment]
ready!

**Comment by lhilarides** [comment]
That's quick! I can confirm the net change layer works now, but the mangrove extent layer seems to still not function. If you could fix that one too and deploy to production (assuming it's a low risk patch) that would be great

**Comment by mluena** [comment]
fixed!

**Comment by klongleywood** [comment]
Tested and confirmed QC
