### ISSUE TITLE
Enhancement: make entire widget header clickable to expand/collapse widget

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#968]
Currently, users need to click on the text in the widget header in order to make it collapse or expand. Can we change this so that the entire header area becomes clickable? See below:
![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/1dfcf1ce-6932-40eb-93ca-6642ea9815fd)

**Comment by klongleywood** [comment]
Tested and confirmed QC
