### ISSUE TITLE
Bug: Mangrove net change layer - many tiles not displayed on different zoom levels

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#970]
When looking at the mangrove net change layer, I noticed that not all tiles are displayed at all zoom levels. 

I can replicate this example below on multiple machines, with multiple browsers, so it's likely to be a data issue
![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/46da465e-6183-43ca-a995-4b3df9a3867a)

Corresponding console error messages:
![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/e5383dec-3e87-4fdd-935e-738394100736)

It looks like different tiles are missing from the tileset at different zoom levels, both for the loss and the gain layers of different years

**Comment by lhilarides** [comment]
Could this issue be picked up @dhakelila ? Thanks!

**Comment by dhakelila** [comment]
@lhilarides , we were regenerating the layers. Let me see the progress. 

@AngelArcones , @mluena

**Comment by klongleywood** [comment]
@mluena and fyi @lhilarides this seems to be working better in the vercel staging environment but there are still issues on the live site

**Comment by lhilarides** [comment]
I've also checked the vercel site, and indeed the layer seems to be working fine there
